// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'main.dart';

mixin BData {
  static B fromJson(Map<String, dynamic> json) {
    return B(
      name: json['name'] as String,
      base: (json['base'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B;
    return <String, dynamic>{
      'type': 'B',
      'name': v.name,
      'base': v.base,
    };
  }

  B copyWith({
    String? name,
    int? base,
  }) {
    final v = this as B;
    return B(
      name: name ?? v.name,
      base: base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.name,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{name: ${v.name}, base: ${v.base}}';
  }
}

mixin DataData {
  static Data fromJson(Map<String, dynamic> json) {
    return Data(
      a: json['a'] as String,
      b: BData.fromJson(json['b'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Data;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b.toJson(),
    };
  }

  Data copyWith({
    String? a,
    B? b,
  }) {
    final v = this as Data;
    return Data(
      a: a ?? v.a,
      b: b ?? v.b,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Data;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Data &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b));
  }

  @override
  int get hashCode {
    final v = this as Data;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
    );
  }

  @override
  String toString() {
    final v = this as Data;
    return 'Data{a: ${v.a}, b: ${v.b}}';
  }
}

mixin AData<T> {
  static A<T> fromJson<T, CT, C2T>(
    Map<String, dynamic> json, {
    required CT Function(Object? v) fromJsonCT,
    required C2T Function(Object? v) fromJsonC2T,
  }) {
    final type = json['type'];
    return switch (type) {
          'B' => BData.fromJson(json),
          'its_c' => CData.fromJson<CT>(json, fromJsonCT),
          'its_c2' => C2Data.fromJson<C2T>(json, fromJsonC2T),
          _ when E.filter(json) => EData.fromJson(json),
          _ => throw InvalidDiscriminatorException(
            'Unrecognized discriminator value "$type" for A. No default subtype is defined.',
          ),
        }
        as A<T>;
  }

  Map<String, dynamic> toJsonBy<CT, C2T>({
    required Object? Function(CT value) toJsonCT,
    required Object? Function(C2T value) toJsonC2T,
  }) {
    return switch (this) {
      B v => v.toJson(),
      C<CT> v => v.toJson(toJsonCT),
      C2<C2T> v => v.toJson(toJsonC2T),
      E v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for A.'),
    };
  }

  Res map<CT, C2T, Res>({
    required Res Function(B value) b,
    required Res Function(C<CT> value) c,
    required Res Function(C2<C2T> value) c2,
    required Res Function(E value) e,
    Res Function(A<T> value)? fallback,
  }) {
    return switch (this) {
      B v => b(v),
      C<CT> v => c(v),
      C2<C2T> v => c2(v),
      E v => e(v),
      _ when fallback != null => fallback(this as A<T>),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for A.'),
    };
  }

  Res? mapOrNull<CT, C2T, Res>({
    Res? Function(B value)? b,
    Res? Function(C<CT> value)? c,
    Res? Function(C2<C2T> value)? c2,
    Res? Function(E value)? e,
  }) {
    return switch (this) {
      B v => b?.call(v),
      C<CT> v => c?.call(v),
      C2<C2T> v => c2?.call(v),
      E v => e?.call(v),
      _ => null,
    };
  }

  A<T> copyWithBy<CT, C2T>({
    B Function(B value)? b,
    C<CT> Function(C<CT> value)? c,
    C2<C2T> Function(C2<C2T> value)? c2,
    E Function(E value)? e,
  }) {
    return switch (this) {
          B v => b != null ? b(v) : v.copyWith(),
          C<CT> v => c != null ? c(v) : v.copyWith(),
          C2<C2T> v => c2 != null ? c2(v) : v.copyWith(),
          E v => e != null ? e(v) : v.copyWith(),
          _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for A.'),
        }
        as A<T>;
  }
}

mixin CData<T> {
  static C<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return C<T>(
      name2: json['name2'] as String,
      val: fromJsonT(json['val']),
      base: (json['base'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as C<T>;
    return <String, dynamic>{
      'type': 'its_c',
      'name2': v.name2,
      'val': toJsonT(v.val),
      'base': v.base,
    };
  }

  C copyWith({
    String? name2,
    T? val,
    int? base,
  }) {
    final v = this as C<T>;
    return C(
      name2: name2 ?? v.name2,
      val: val ?? v.val,
      base: base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as C<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is C<T> &&
            (identical(other.name2, v.name2) || other.name2 == v.name2) &&
            (identical(other.val, v.val) || other.val == v.val) &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as C<T>;
    return Object.hash(
      runtimeType,
      v.name2,
      v.val,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as C<T>;
    return 'C<$T>{name2: ${v.name2}, val: ${v.val}, base: ${v.base}}';
  }
}

mixin EData {
  static E fromJson(Map<String, dynamic> json) {
    return E(
      name2: json['name2'] as String,
      base: (json['base'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as E;
    return <String, dynamic>{
      'name2': v.name2,
      'base': v.base,
    };
  }

  E copyWith({
    String? name2,
    int? base,
  }) {
    final v = this as E;
    return E(
      name2: name2 ?? v.name2,
      base: base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as E;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is E &&
            (identical(other.name2, v.name2) || other.name2 == v.name2) &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as E;
    return Object.hash(
      runtimeType,
      v.name2,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as E;
    return 'E{name2: ${v.name2}, base: ${v.base}}';
  }
}

mixin C2Data<T> {
  static C2<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return C2<T>(
      name2: json['name2'] as String,
      base: fromJsonT(json['base']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as C2<T>;
    return <String, dynamic>{
      'type': 'its_c2',
      'name2': v.name2,
      'base': toJsonT(v.base),
    };
  }

  C2 copyWith({
    String? name2,
    T? base,
  }) {
    final v = this as C2<T>;
    return C2(
      name2: name2 ?? v.name2,
      base: base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as C2<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is C2<T> &&
            (identical(other.name2, v.name2) || other.name2 == v.name2) &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as C2<T>;
    return Object.hash(
      runtimeType,
      v.name2,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as C2<T>;
    return 'C2<$T>{name2: ${v.name2}, base: ${v.base}}';
  }
}

mixin AnimalData {
  static Animal fromJson(Map<String, dynamic> json) {
    final type = json['type'];
    return switch (type) {
      'Cat' => CatData.fromJson(json),
      'Cow' => CowData.fromJson(json),
      'its_dog' => DogData.fromJson(json),
      _ => throw InvalidDiscriminatorException(
        'Unrecognized discriminator value "$type" for Animal. No default subtype is defined.',
      ),
    };
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      Cat v => v.toJson(),
      Cow v => v.toJson(),
      Dog v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res map<Res>({
    required Res Function(Cat value) cat,
    required Res Function(Cow value) cow,
    required Res Function(Dog value) dog,
    Res Function(Animal value)? fallback,
  }) {
    return switch (this) {
      Cat v => cat(v),
      Cow v => cow(v),
      Dog v => dog(v),
      _ when fallback != null => fallback(this as Animal),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(Cat value)? cat,
    Res? Function(Cow value)? cow,
    Res? Function(Dog value)? dog,
  }) {
    return switch (this) {
      Cat v => cat?.call(v),
      Cow v => cow?.call(v),
      Dog v => dog?.call(v),
      _ => null,
    };
  }

  Animal copyWithBy({Cat Function(Cat value)? cat, Cow Function(Cow value)? cow, Dog Function(Dog value)? dog}) {
    return switch (this) {
      Cat v => cat != null ? cat(v) : v.copyWith(),
      Cow v => cow != null ? cow(v) : v.copyWith(),
      Dog v => dog != null ? dog(v) : v.copyWith(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }
}

mixin CatData {
  static Cat fromJson(Map<String, dynamic> json) {
    return Cat(
      nickName: json['nickName'] as String,
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Cat;
    return <String, dynamic>{
      'type': 'Cat',
      'nickName': v.nickName,
      'name': v.name,
    };
  }

  Cat copyWith({
    String? nickName,
    String? name,
  }) {
    final v = this as Cat;
    return Cat(
      nickName: nickName ?? v.nickName,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Cat;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Cat &&
            (identical(other.nickName, v.nickName) || other.nickName == v.nickName) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Cat;
    return Object.hash(
      runtimeType,
      v.nickName,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Cat;
    return 'Cat{nickName: ${v.nickName}, name: ${v.name}}';
  }
}

mixin DogData {
  static Dog fromJson(Map<String, dynamic> json) {
    return Dog(
      big: json['big'] as bool,
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Dog;
    return <String, dynamic>{
      'type': 'its_dog',
      'big': v.big,
      'name': v.name,
    };
  }

  Dog copyWith({
    bool? big,
    String? name,
  }) {
    final v = this as Dog;
    return Dog(
      big: big ?? v.big,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Dog;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Dog &&
            (identical(other.big, v.big) || other.big == v.big) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Dog;
    return Object.hash(
      runtimeType,
      v.big,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Dog;
    return 'Dog{big: ${v.big}, name: ${v.name}}';
  }
}

mixin CowData {
  static Cow fromJson(Map<String, dynamic> json) {
    return Cow(
      big: json['big'] as bool,
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Cow;
    return <String, dynamic>{
      'big': v.big,
      'name': v.name,
    };
  }

  Cow copyWith({
    bool? big,
    String? name,
  }) {
    final v = this as Cow;
    return Cow(
      big: big ?? v.big,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Cow;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Cow &&
            (identical(other.big, v.big) || other.big == v.big) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Cow;
    return Object.hash(
      runtimeType,
      v.big,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Cow;
    return 'Cow{big: ${v.big}, name: ${v.name}}';
  }
}

mixin BbData {
  static Bb fromJson(Map<String, dynamic> json) {
    return Bb();
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{};
  }

  Bb copyWith() {
    return Bb();
  }

  @override
  bool operator ==(Object other) {
    return identical(this, other) || (other.runtimeType == runtimeType && other is Bb);
  }

  @override
  int get hashCode {
    return Object.hashAll([
      runtimeType,
    ]);
  }

  @override
  String toString() {
    return 'Bb{}';
  }
}

mixin CccData {
  static Ccc fromJson(Map<String, dynamic> json) {
    return Ccc(
      json['a'] as String,
      json['b'] as String,
      d: json['d'] as String?,
      e: json['e'] as String?,
      aaaaa: json['cccusjtokkhjjmdd'] == null ? null : Ccc.aFromJson(json['cccusjtokkhjjmdd'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Ccc;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'd': ?v.d,
      'e': ?v.e,
      'cccusjtokkhjjmdd': ?Ccc.aToJson(v.aaaaa),
    };
  }

  Ccc copyWith({
    String? a,
    String? b,
    String? d,
    String? e,
    Aaa<int>? aaaaa,
  }) {
    final v = this as Ccc;
    return Ccc(
      a ?? v.a,
      b ?? v.b,
      d: d ?? v.d,
      e: e ?? v.e,
      aaaaa: aaaaa ?? v.aaaaa,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Ccc;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Ccc &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.e, v.e) || other.e == v.e) &&
            (identical(other.aaaaa, v.aaaaa) || other.aaaaa == v.aaaaa));
  }

  @override
  int get hashCode {
    final v = this as Ccc;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.d,
      v.e,
      v.aaaaa,
    );
  }

  @override
  String toString() {
    final v = this as Ccc;
    return 'Ccc{a: ${v.a}, b: ${v.b}, d: ${v.d}, e: ${v.e}, aaaaa: ${v.aaaaa}}';
  }
}

mixin AaaData<T> {
  static Aaa<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Aaa<T>(
      genericData: (json['genData'] as List<dynamic>)
          .map((e) => (e as List<dynamic>).map((e) => fromJsonT(e)).toList())
          .toList(),
      data: Aaa.strFromJson(json['data'] as Object?),
      b: BbData.fromJson(json['data2'] as Map<String, dynamic>),
      c: BbData.fromJson(json['dataC'] as Map<String, dynamic>),
      data3: (json['data3'] as List<dynamic>).map((e) => e as String).toList(),
      customEnum: MacroExt.decodeEnum(MyEnumData.values, json['customEnum'], unknownValue: null),
      d: CccData.fromJson(json['dataD'] as Map<String, dynamic>),
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Aaa<T>;
    return <String, dynamic>{
      'genData': v.genericData.map((e) => e.map((e) => toJsonT(e)).toList()).toList(),
      'data': Aaa.strToJson(v.data),
      'data2': v.b.toJson(),
      'dataC': v.c.toJson(),
      'data3': v.data3,
      'customEnum': v.customEnum.name,
      'dataD': v.d.toJson(),
      'name': v.name,
    };
  }

  Aaa copyWith({
    List<List<T>>? genericData,
    int? data,
    Bb? b,
    Bb? c,
    List<String>? data3,
    MyEnumData? customEnum,
    Ccc? d,
    String? name,
  }) {
    final v = this as Aaa<T>;
    return Aaa(
      genericData: genericData ?? v.genericData,
      data: data ?? v.data,
      b: b ?? v.b,
      c: c ?? v.c,
      data3: data3 ?? v.data3,
      customEnum: customEnum ?? v.customEnum,
      d: d ?? v.d,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Aaa<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Aaa<T> &&
            const DeepCollectionEquality().equals(other.genericData, v.genericData) &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.c, v.c) || other.c == v.c) &&
            const DeepCollectionEquality().equals(other.data3, v.data3) &&
            (identical(other.customEnum, v.customEnum) || other.customEnum == v.customEnum) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Aaa<T>;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.genericData),
      v.data,
      v.b,
      v.c,
      const DeepCollectionEquality().hash(v.data3),
      v.customEnum,
      v.d,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Aaa<T>;
    return 'Aaa<$T>{genericData: ${v.genericData}, data: ${v.data}, b: ${v.b}, c: ${v.c}, data3: ${v.data3}, customEnum: ${v.customEnum}, d: ${v.d}, name: ${v.name}}';
  }
}

mixin TestData<T1, T2, T3, T4> {
  static Test<T1, T2, T3, T4> fromJson<T1, T2, T3, T4>(
    Map<String, dynamic> json,
    T1 Function(Object? v) fromJsonT1,
    T2 Function(Object? v) fromJsonT2,
    T3 Function(Object? v) fromJsonT3,
    T4 Function(Object? v) fromJsonT4,
  ) {
    return Test<T1, T2, T3, T4>(
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson(
    Object? Function(T1 v) toJsonT1,
    Object? Function(T2 v) toJsonT2,
    Object? Function(T3 v) toJsonT3,
    Object? Function(T4 v) toJsonT4,
  ) {
    final v = this as Test<T1, T2, T3, T4>;
    return <String, dynamic>{
      'name': v.name,
    };
  }

  Test copyWith({
    String? name,
  }) {
    final v = this as Test<T1, T2, T3, T4>;
    return Test(
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Test<T1, T2, T3, T4>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Test<T1, T2, T3, T4> &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Test<T1, T2, T3, T4>;
    return Object.hash(
      runtimeType,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Test<T1, T2, T3, T4>;
    return 'Test<$T1,T2,T3,T4>{name: ${v.name}}';
  }
}
