// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: invalid_use_of_internal_member, unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

import 'dart:typed_data';

import 'package:macro_kit/macro_kit.dart';

import 'images/flutter.dart' as i3356018501;
import 'images/dart.dart' as i3657187921;
import './butterfly.dart' as i2123351816;

/// The main entry point for accessing the embedded file system.
///
/// This class provides static factory methods to create [EmbedFile] and
/// [EmbedDirectory] instances that access files embedded at compile time.    
final class EmbedFS {
  EmbedFS._();
  
  static final _EmbedRegistryImpl _registry = _EmbedRegistryImpl._();
  
  /// Creates an [EmbedFile] instance for the file at the given [path].
  ///
  /// The [path] should be an absolute path (starting with '/') that matches
  /// a file embedded during the macro generation phase.
  ///
  /// Example:
  /// ```dart
  /// final logo = EmbedFS.file('/images/logo.png');
  /// final bytes = logo.readAsBytesSync();
  /// ```
  ///
  /// Returns an [EmbedFile] that can be used to read the file's contents.
  static EmbedFile file(String path) => EmbedFile(path)..$registry = _registry;
  
  /// Creates an [EmbedDirectory] instance for the directory at the given [path].
  ///
  /// The [path] should be an absolute path (starting with '/') to a directory
  /// in the embedded file system.
  ///
  /// Example:
  /// ```dart
  /// final assets = EmbedFS.directory('/assets');
  /// final children = assets.listSync();
  /// ```
  ///
  /// Returns an [EmbedDirectory] that can be used to list its contents.
  static EmbedDirectory directory(String path) => EmbedDirectory(path)..$registry = _registry;
  
  /// Returns the root directory ('/') of the embedded file system.
  ///
  /// This is a convenience getter equivalent to calling `directory('/')`.
  /// Use this as a starting point to explore all embedded files.
  ///
  /// Example:
  /// ```dart
  /// final root = EmbedFS.current;
  /// final allFiles = root.listSync(recursive: true);
  /// ```
  ///
  /// Returns an [EmbedDirectory] representing the root of the file system.
  static EmbedDirectory get current => directory('/');
}    
    
final class _EmbedRegistryImpl implements EmbedRegistry {   
  _EmbedRegistryImpl._();
   
  final cache = <String, Uint8List>{};

  void clearCache() => cache.clear();

  List<String> get allPaths => _files.keys.toList();

  bool exists(String path) => _files.containsKey(path);

  Uint8List? readBytes(String path) => _files[path]?.call();

  final Map<String, Uint8List Function()> _files = {
    '/assets/images/flutter.jpg': () => i3356018501.flutterData,
    '/assets/images/dart.svg': () => i3657187921.dartData,
    '/assets/butterfly.jpg': () => i2123351816.butterflyData,
  };

}
