// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'dart_type_test.dart';

mixin UserProfileData {
  static UserProfile fromJson(Map<String, dynamic> json) {
    return UserProfile(
      name: json['name'] as String,
      age: (json['age'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile;
    return <String, dynamic>{
      'name': v.name,
      'age': v.age,
    };
  }

  UserProfile copyWith({
    String? name,
    int? age,
  }) {
    final v = this as UserProfile;
    return UserProfile(
      name: name ?? v.name,
      age: age ?? v.age,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age));
  }

  @override
  int get hashCode {
    final v = this as UserProfile;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile;
    return 'UserProfile{name: ${v.name}, age: ${v.age}}';
  }
}

class TestCustom {
  final types = <String, Object>{
    'singleType': UserProfile,
    'list0Type': UserProfile,
    'list1Type': int,
    'list2Type': String,
    'f1Type': String,
    'f1Set2Type0': String,
    'f1List1Type0': String,
    'f1List1Type1': int,
    'f1List2Type00': int,
    'f1List3Type00': int,
    'f1List3Type01': double,
    'f1Map1TypeA0': Future<String>,
    'f1Map2TypeA200': bool,
    'f1Map3TypeA3000': double,
    'f2Type': int,
    'f3Type': UserProfile,
    'f4Type': List<int>,
    'f5Type': List<UserProfile>,
    'f6Type': List<Type>,
  };
}
