// ignore_for_file: library_private_types_in_public_api
// Generated by AssetPathMacro: DO NOT MODIFY BY HAND

final class AssetPaths {
  const AssetPaths._();

  static const butterfly = 'assets/butterfly.jpg';

  static const _Images images = _Images._();
}

final class _Images {
  const _Images._();

  static const flutterVal = 'assets/images/flutter.jpg';

  String get flutter => flutterVal;
  static const dartVal = 'assets/images/dart.svg';

  String get dart => dartVal;
}
