// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'example3.dart';

mixin AnimalData {
  static Animal fromJson(Map<String, dynamic> json) {
    final type = json['type'];
    return switch (type) {
      'Cat' => CatData.fromJson(json),
      _ when Dog.checkIsDog(json) => DogData.fromJson(json),
      _ => throw InvalidDiscriminatorException(
        'Unrecognized discriminator value "$type" for Animal. No default subtype is defined.',
      ),
    };
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      Cat v => v.toJson(),
      Dog v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res map<Res>({
    required Res Function(Cat value) cat,
    required Res Function(Dog value) dog,
    Res Function(Animal value)? fallback,
  }) {
    return switch (this) {
      Cat v => cat(v),
      Dog v => dog(v),
      _ when fallback != null => fallback(this as Animal),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(Cat value)? cat,
    Res? Function(Dog value)? dog,
  }) {
    return switch (this) {
      Cat v => cat?.call(v),
      Dog v => dog?.call(v),
      _ => null,
    };
  }

  Animal copyWithBy({
    Cat Function(Cat value)? cat,
    Dog Function(Dog value)? dog,
  }) {
    return switch (this) {
      Cat v => cat != null ? cat(v) : v.copyWith(),
      Dog v => dog != null ? dog(v) : v.copyWith(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  @pragma('vm:prefer-inline')
  Cat asCat() {
    return this as Cat;
  }

  @pragma('vm:prefer-inline')
  Dog asDog() {
    return this as Dog;
  }

  static Schema get schema {
    return S.combined(
      title: 'Animal',
      description: 'Schema for Animal',
      anyOf: [
        S.object(
          title: 'Cat',
          required: ['name', 'type'],
          properties: {
            'type': S.string(
              description: 'Type discriminator',
              enumValues: ['Cat'],
            ),
            'name': S.string(),
          },
          additionalProperties: false,
        ),
        S.object(
          title: 'Dog',
          required: ['name'],
          properties: {
            'name': S.string(),
          },
          additionalProperties: false,
        ),
      ],
    );
  }
}

mixin CatData {
  static Cat fromJson(Map<String, dynamic> json) {
    return Cat(
      name: json['name'] as String,
      nickName: json['nickName'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Cat;
    return <String, dynamic>{
      'name': v.name,
      'nickName': v.nickName,
      'type': 'Cat',
    };
  }

  Cat copyWith({
    String? name,
    String? nickName,
  }) {
    final v = this as Cat;
    return Cat(
      name: name ?? v.name,
      nickName: nickName ?? v.nickName,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Cat;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Cat &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.nickName, v.nickName) || other.nickName == v.nickName));
  }

  @override
  int get hashCode {
    final v = this as Cat;
    return Object.hash(
      runtimeType,
      v.name,
      v.nickName,
    );
  }

  @override
  String toString() {
    final v = this as Cat;
    return 'Cat{name: ${v.name}, nickName: ${v.nickName}}';
  }

  static Schema get schema {
    return S.object(
      title: 'Cat',
      description: 'Schema for Cat',
      required: ['name', 'nickName'],
      properties: {
        'name': S.string(),
        'nickName': S.string(),
      },
      additionalProperties: false,
    );
  }
}

mixin DogData {
  static Dog fromJson(Map<String, dynamic> json) {
    return Dog(
      name: json['name'] as String,
      big: json['big'] as bool,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Dog;
    return <String, dynamic>{
      'name': v.name,
      'big': v.big,
    };
  }

  Dog copyWith({
    String? name,
    bool? big,
  }) {
    final v = this as Dog;
    return Dog(
      name: name ?? v.name,
      big: big ?? v.big,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Dog;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Dog &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.big, v.big) || other.big == v.big));
  }

  @override
  int get hashCode {
    final v = this as Dog;
    return Object.hash(
      runtimeType,
      v.name,
      v.big,
    );
  }

  @override
  String toString() {
    final v = this as Dog;
    return 'Dog{name: ${v.name}, big: ${v.big}}';
  }

  static Schema get schema {
    return S.object(
      title: 'Dog',
      description: 'Schema for Dog',
      required: ['name', 'big'],
      properties: {
        'name': S.string(),
        'big': S.boolean(),
      },
      additionalProperties: false,
    );
  }
}
