// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'main.dart';

mixin UserProfile2Data {
  static UserProfile2 fromJson(Map<String, dynamic> json) {
    return UserProfile2(
      username: json['username'] as String,
      email: json['email'] as String,
      age: (json['age'] as num?)?.toInt(),
      roles: (json['roles'] as List<dynamic>?)?.map((e) => e as String).toList(),
      customData: (json['CustomData'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile2;
    return <String, dynamic>{
      'username': v.username,
      'email': v.email,
      'age': ?v.age,
      'roles': ?v.roles,
      'CustomData': v.customData,
    };
  }

  UserProfile2 copyWith({
    String? username,
    String? email,
    int? age,
    List<String>? roles,
    int? customData,
  }) {
    final v = this as UserProfile2;
    return UserProfile2(
      username: username ?? v.username,
      email: email ?? v.email,
      age: age ?? v.age,
      roles: roles ?? v.roles,
      customData: customData ?? v.customData,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile2 &&
            (identical(other.username, v.username) || other.username == v.username) &&
            (identical(other.email, v.email) || other.email == v.email) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            const DeepCollectionEquality().equals(other.roles, v.roles) &&
            (identical(other.customData, v.customData) || other.customData == v.customData));
  }

  @override
  int get hashCode {
    final v = this as UserProfile2;
    return Object.hash(
      runtimeType,
      v.username,
      v.email,
      v.age,
      const DeepCollectionEquality().hash(v.roles),
      v.customData,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile2;
    return 'UserProfile2{username: ${v.username}, email: ${v.email}, age: ${v.age}, roles: ${v.roles}, customData: ${v.customData}}';
  }

  static Schema get schema {
    return S.object(
      title: 'UserProfile2',
      description: 'Schema for UserProfile2',
      required: ['username', 'email', 'CustomData'],
      properties: {
        'username': S.string(),
        'email': S.string(),
        'age': S.integer(),
        'roles': S.list(
          items: S.string(),
        ),
        'CustomData': S.integer(),
      },
      additionalProperties: false,
    );
  }
}

mixin _MyHomePageStateForm {
  // Value notifiers for form fields
  final nameState = ValueNotifier(Optional<String>.undefined());
  final ageState = ValueNotifier(Optional<int>.undefined());
  final profileState = ValueNotifier(Optional<UserProfile2>.undefined());
  final myListState = ValueNotifier(Optional<List<String>>.value(['a', 'b', 'c']));

  // Getters and setters for form fields
  String? get name {
    final opt = nameState.value;
    return opt.isSet ? opt.value : null;
  }

  set name(String? value) {
    if (value == null) {
      nameState.value = Optional<String>.nullValue();
    } else {
      nameState.value = Optional<String>.value(value);
    }
  }

  int? get age {
    final opt = ageState.value;
    return opt.isSet ? opt.value : null;
  }

  set age(int? value) {
    if (value == null) {
      ageState.value = Optional<int>.nullValue();
    } else {
      ageState.value = Optional<int>.value(value);
    }
  }

  UserProfile2? get profile {
    final opt = profileState.value;
    return opt.isSet ? opt.value : null;
  }

  set profile(UserProfile2? value) {
    if (value == null) {
      profileState.value = Optional<UserProfile2>.nullValue();
    } else {
      profileState.value = Optional<UserProfile2>.value(value);
    }
  }

  List<String>? get myList {
    final opt = myListState.value;
    return opt.isSet ? opt.value : null;
  }

  set myList(List<String>? value) {
    if (value == null) {
      myListState.value = Optional<List<String>>.nullValue();
    } else {
      myListState.value = Optional<List<String>>.value(value);
    }
  }

  // Dispose all value notifiers
  void dispose() {
    nameState.dispose();
    ageState.dispose();
    profileState.dispose();
    myListState.dispose();
  }
}
