// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'type.dart';

const __buttonStylesHash = 4054003751;

class ButtonStyles {
  ButtonStyles._();

  static const primary = ButtonStyle(
    backgroundColor: MaterialStatePropertyAll(Color(4281558783)),
    foregroundColor: MaterialStatePropertyAll(Color(4294967295)),
    shape: MaterialStatePropertyAll(
      RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(12.0))),
    ),
  );

  static const danger = ButtonStyle(
    backgroundColor: MaterialStatePropertyAll(Color(4293212469)),
    foregroundColor: MaterialStatePropertyAll(Color(4294967295)),
    shape: MaterialStatePropertyAll(
      RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(12.0))),
    ),
  );

  static const ghost = ButtonStyle(
    backgroundColor: MaterialStatePropertyAll(Color(0)),
    foregroundColor: MaterialStatePropertyAll(Color(4281558783)),
    shape: MaterialStatePropertyAll(
      RoundedRectangleBorder(borderRadius: BorderRadius.all(Radius.circular(12.0))),
    ),
  );
}

const __routeEnumHash = 1049475900;

enum AppRoute {
  home('/home'),
  search('/search'),
  profile('/profile');

  final String path;
  const AppRoute(this.path);
}
