// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'class_equality_test.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      json['a'] as String,
      b: (json['b'] as num?)?.toInt() ?? 0,
      c: (json['c'] as num?)?.toDouble(),
      d: json['d'] as bool,
      e: MacroExt.decodeNullableEnum(B.values, json['e'], unknownValue: null),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'c': ?v.c,
      'd': v.d,
      'e': ?v.e?.name,
    };
  }

  A copyWith({
    String? a,
    int? b,
    double? c,
    bool? d,
    B? e,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
      b: b ?? v.b,
      c: c ?? v.c,
      d: d ?? v.d,
      e: e ?? v.e,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.c, v.c) || other.c == v.c) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.e, v.e) || other.e == v.e));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.c,
      v.d,
      v.e,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}, c: ${v.c}, d: ${v.d}, e: ${v.e}}';
  }
}

mixin BaseData {
  static Base fromJson(Map<String, dynamic> json) {
    final type = json['type'];
    return switch (type) {
      'Sub' => SubData.fromJson(json),
      'Sub2' => Sub2Data.fromJson(json),
      _ => throw InvalidDiscriminatorException(
        'Unrecognized discriminator value "$type" for Base. No default subtype is defined.',
      ),
    };
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      Sub v => v.toJson(),
      Sub2 v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Base.'),
    };
  }

  Res map<Res>({
    required Res Function(Sub value) sub,
    required Res Function(Sub2 value) sub2,
    Res Function(Base value)? fallback,
  }) {
    return switch (this) {
      Sub v => sub(v),
      Sub2 v => sub2(v),
      _ when fallback != null => fallback(this as Base),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Base.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(Sub value)? sub,
    Res? Function(Sub2 value)? sub2,
  }) {
    return switch (this) {
      Sub v => sub?.call(v),
      Sub2 v => sub2?.call(v),
      _ => null,
    };
  }

  Base copyWithBy({
    Sub Function(Sub value)? sub,
    Sub2 Function(Sub2 value)? sub2,
  }) {
    return switch (this) {
      Sub v => sub != null ? sub(v) : v.copyWith(),
      Sub2 v => sub2 != null ? sub2(v) : v.copyWith(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Base.'),
    };
  }

  @pragma('vm:prefer-inline')
  Sub asSub() {
    return this as Sub;
  }

  @pragma('vm:prefer-inline')
  Sub2 asSub2() {
    return this as Sub2;
  }
}

mixin SubData {
  static Sub fromJson(Map<String, dynamic> json) {
    return Sub(
      json['data'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Sub;
    return <String, dynamic>{
      'data': v.data,
      'type': 'Sub',
    };
  }

  Sub copyWith({
    String? data,
  }) {
    final v = this as Sub;
    return Sub(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Sub;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is Sub && (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as Sub;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as Sub;
    return 'Sub{data: ${v.data}}';
  }
}

mixin Sub2Data {
  static Sub2 fromJson(Map<String, dynamic> json) {
    return Sub2(
      json['data'] as String,
      json['data2'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Sub2;
    return <String, dynamic>{
      'data': v.data,
      'data2': v.data2,
      'type': 'Sub2',
    };
  }

  Sub2 copyWith({
    String? data,
    String? data2,
  }) {
    final v = this as Sub2;
    return Sub2(
      data ?? v.data,
      data2 ?? v.data2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Sub2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Sub2 &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2));
  }

  @override
  int get hashCode {
    final v = this as Sub2;
    return Object.hash(
      runtimeType,
      v.data,
      v.data2,
    );
  }

  @override
  String toString() {
    final v = this as Sub2;
    return 'Sub2{data: ${v.data}, data2: ${v.data2}}';
  }
}

mixin BaseTypeData {
  static BaseType fromJson(Map<String, dynamic> json) {
    final type = json['disType'];
    return switch (type) {
      'SubType1' => SubTypeData.fromJson(json),
      'SubType2' => SubType2Data.fromJson(json),
      _ => throw InvalidDiscriminatorException(
        'Unrecognized discriminator value "$type" for BaseType. No default subtype is defined.',
      ),
    };
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      SubType v => v.toJson(),
      SubType2 v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseType.'),
    };
  }

  Res map<Res>({
    required Res Function(SubType value) subType,
    required Res Function(SubType2 value) subType2,
    Res Function(BaseType value)? fallback,
  }) {
    return switch (this) {
      SubType v => subType(v),
      SubType2 v => subType2(v),
      _ when fallback != null => fallback(this as BaseType),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseType.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(SubType value)? subType,
    Res? Function(SubType2 value)? subType2,
  }) {
    return switch (this) {
      SubType v => subType?.call(v),
      SubType2 v => subType2?.call(v),
      _ => null,
    };
  }

  BaseType copyWithBy({
    SubType Function(SubType value)? subType,
    SubType2 Function(SubType2 value)? subType2,
  }) {
    return switch (this) {
      SubType v => subType != null ? subType(v) : v.copyWith(),
      SubType2 v => subType2 != null ? subType2(v) : v.copyWith(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseType.'),
    };
  }

  @pragma('vm:prefer-inline')
  SubType asSubType() {
    return this as SubType;
  }

  @pragma('vm:prefer-inline')
  SubType2 asSubType2() {
    return this as SubType2;
  }
}

mixin SubTypeData {
  static SubType fromJson(Map<String, dynamic> json) {
    return SubType(
      json['type'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as SubType;
    return <String, dynamic>{
      'type': v.type,
      'disType': 'SubType1',
    };
  }

  SubType copyWith({
    String? type,
  }) {
    final v = this as SubType;
    return SubType(
      type ?? v.type,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as SubType;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is SubType &&
            (identical(other.type, v.type) || other.type == v.type));
  }

  @override
  int get hashCode {
    final v = this as SubType;
    return Object.hash(
      runtimeType,
      v.type,
    );
  }

  @override
  String toString() {
    final v = this as SubType;
    return 'SubType{type: ${v.type}}';
  }
}

mixin SubType2Data {
  static SubType2 fromJson(Map<String, dynamic> json) {
    return SubType2(
      json['type'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as SubType2;
    return <String, dynamic>{
      'type': v.type,
      'disType': 'SubType2',
    };
  }

  SubType2 copyWith({
    String? type,
  }) {
    final v = this as SubType2;
    return SubType2(
      type ?? v.type,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as SubType2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is SubType2 &&
            (identical(other.type, v.type) || other.type == v.type));
  }

  @override
  int get hashCode {
    final v = this as SubType2;
    return Object.hash(
      runtimeType,
      v.type,
    );
  }

  @override
  String toString() {
    final v = this as SubType2;
    return 'SubType2{type: ${v.type}}';
  }
}

mixin GenericData<T> {
  static Generic<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Generic<T>(
      fromJsonT(json['data']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Generic<T>;
    return <String, dynamic>{
      'data': toJsonT(v.data),
    };
  }

  Generic<T> copyWith({
    T? data,
  }) {
    final v = this as Generic<T>;
    return Generic<T>(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Generic<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Generic<T> &&
            (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as Generic<T>;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as Generic<T>;
    return 'Generic<$T>{data: ${v.data}}';
  }
}

mixin WrapperData<T> {
  static Wrapper<T> fromJson<T>(
    Map<String, dynamic> json,
    T Function(Object? v) fromJsonT,
    String Function(Object? v) fromJsonValue2,
  ) {
    return Wrapper<T>(
      GenericData.fromJson<T>(json['value1'] as Map<String, dynamic>, fromJsonT),
      GenericData.fromJson<String>(json['value2'] as Map<String, dynamic>, fromJsonValue2),
      fromJsonT(json['value3']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT, Object? Function(String v) toJsonValue2) {
    final v = this as Wrapper<T>;
    return <String, dynamic>{
      'value1': v.value1.toJson(toJsonT),
      'value2': v.value2.toJson(toJsonValue2),
      'value3': toJsonT(v.value3),
    };
  }

  Wrapper<T> copyWith({
    Generic<T>? value1,
    Generic<String>? value2,
    T? value3,
  }) {
    final v = this as Wrapper<T>;
    return Wrapper<T>(
      value1 ?? v.value1,
      value2 ?? v.value2,
      value3 ?? v.value3,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Wrapper<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Wrapper<T> &&
            (identical(other.value1, v.value1) || other.value1 == v.value1) &&
            (identical(other.value2, v.value2) || other.value2 == v.value2) &&
            (identical(other.value3, v.value3) || other.value3 == v.value3));
  }

  @override
  int get hashCode {
    final v = this as Wrapper<T>;
    return Object.hash(
      runtimeType,
      v.value1,
      v.value2,
      v.value3,
    );
  }

  @override
  String toString() {
    final v = this as Wrapper<T>;
    return 'Wrapper<$T>{value1: ${v.value1}, value2: ${v.value2}, value3: ${v.value3}}';
  }
}

mixin Wrapper2Data<T, E> {
  static Wrapper2<T, E> fromJson<T, E>(
    Map<String, dynamic> json,
    T Function(Object? v) fromJsonT,
    E Function(Object? v) fromJsonE,
    String Function(Object? v) fromJsonValue2,
  ) {
    return Wrapper2<T, E>(
      GenericData.fromJson<T>(json['value1'] as Map<String, dynamic>, fromJsonT),
      GenericData.fromJson<String>(json['value2'] as Map<String, dynamic>, fromJsonValue2),
      fromJsonT(json['value3']),
    );
  }

  Map<String, dynamic> toJson(
    Object? Function(T v) toJsonT,
    Object? Function(E v) toJsonE,
    Object? Function(String v) toJsonValue2,
  ) {
    final v = this as Wrapper2<T, E>;
    return <String, dynamic>{
      'value1': v.value1.toJson(toJsonT),
      'value2': v.value2.toJson(toJsonValue2),
      'value3': toJsonT(v.value3),
    };
  }

  Wrapper2<T, E> copyWith({
    Generic<T>? value1,
    Generic<String>? value2,
    T? value3,
  }) {
    final v = this as Wrapper2<T, E>;
    return Wrapper2<T, E>(
      value1 ?? v.value1,
      value2 ?? v.value2,
      value3 ?? v.value3,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Wrapper2<T, E>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Wrapper2<T, E> &&
            (identical(other.value1, v.value1) || other.value1 == v.value1) &&
            (identical(other.value2, v.value2) || other.value2 == v.value2) &&
            (identical(other.value3, v.value3) || other.value3 == v.value3));
  }

  @override
  int get hashCode {
    final v = this as Wrapper2<T, E>;
    return Object.hash(
      runtimeType,
      v.value1,
      v.value2,
      v.value3,
    );
  }

  @override
  String toString() {
    final v = this as Wrapper2<T, E>;
    return 'Wrapper2<$T,E>{value1: ${v.value1}, value2: ${v.value2}, value3: ${v.value3}}';
  }
}

mixin BaseTypeGenData<T> {
  static BaseTypeGen<T> fromJson<T>(Map<String, dynamic> json) {
    final type = json['disType'];
    return switch (type) {
          'SubType2Gen' => SubType2GenData.fromJson(json),
          'SubType1' => SubTypeGenData.fromJson(json),
          _ => throw InvalidDiscriminatorException(
            'Unrecognized discriminator value "$type" for BaseTypeGen. No default subtype is defined.',
          ),
        }
        as BaseTypeGen<T>;
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      SubType2Gen v => v.toJson(),
      SubTypeGen v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseTypeGen.'),
    };
  }

  Res map<Res>({
    required Res Function(SubType2Gen value) subType2Gen,
    required Res Function(SubTypeGen value) subTypeGen,
    Res Function(BaseTypeGen<T> value)? fallback,
  }) {
    return switch (this) {
      SubType2Gen v => subType2Gen(v),
      SubTypeGen v => subTypeGen(v),
      _ when fallback != null => fallback(this as BaseTypeGen<T>),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseTypeGen.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(SubType2Gen value)? subType2Gen,
    Res? Function(SubTypeGen value)? subTypeGen,
  }) {
    return switch (this) {
      SubType2Gen v => subType2Gen?.call(v),
      SubTypeGen v => subTypeGen?.call(v),
      _ => null,
    };
  }

  BaseTypeGen<T> copyWithBy({
    SubType2Gen Function(SubType2Gen value)? subType2Gen,
    SubTypeGen Function(SubTypeGen value)? subTypeGen,
  }) {
    return switch (this) {
          SubType2Gen v => subType2Gen != null ? subType2Gen(v) : v.copyWith(),
          SubTypeGen v => subTypeGen != null ? subTypeGen(v) : v.copyWith(),
          _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for BaseTypeGen.'),
        }
        as BaseTypeGen<T>;
  }

  @pragma('vm:prefer-inline')
  SubType2Gen asSubType2Gen() {
    return this as SubType2Gen;
  }

  @pragma('vm:prefer-inline')
  SubTypeGen asSubTypeGen() {
    return this as SubTypeGen;
  }
}

mixin SubTypeGenData {
  static SubTypeGen fromJson(Map<String, dynamic> json) {
    return SubTypeGen(
      json['base'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as SubTypeGen;
    return <String, dynamic>{
      'base': v.base,
      'disType': 'SubType1',
    };
  }

  SubTypeGen copyWith({
    String? base,
  }) {
    final v = this as SubTypeGen;
    return SubTypeGen(
      base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as SubTypeGen;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is SubTypeGen &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as SubTypeGen;
    return Object.hash(
      runtimeType,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as SubTypeGen;
    return 'SubTypeGen{base: ${v.base}}';
  }
}

mixin SubType2GenData {
  static SubType2Gen fromJson(Map<String, dynamic> json) {
    return SubType2Gen(
      json['base'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as SubType2Gen;
    return <String, dynamic>{
      'base': v.base,
      'disType': 'SubType2Gen',
    };
  }

  SubType2Gen copyWith({
    String? base,
  }) {
    final v = this as SubType2Gen;
    return SubType2Gen(
      base ?? v.base,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as SubType2Gen;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is SubType2Gen &&
            (identical(other.base, v.base) || other.base == v.base));
  }

  @override
  int get hashCode {
    final v = this as SubType2Gen;
    return Object.hash(
      runtimeType,
      v.base,
    );
  }

  @override
  String toString() {
    final v = this as SubType2Gen;
    return 'SubType2Gen{base: ${v.base}}';
  }
}
