// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'collection_equality_test.dart';

mixin SetWrapperData {
  static SetWrapper fromJson(Map<String, dynamic> json) {
    return SetWrapper(
      (json['values'] as List<dynamic>).map((e) => e as String).toSet(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as SetWrapper;
    return <String, dynamic>{
      'values': v.values.map((e) => e).toList(),
    };
  }

  SetWrapper copyWith({
    Set<String>? values,
  }) {
    final v = this as SetWrapper;
    return SetWrapper(
      values ?? v.values,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as SetWrapper;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is SetWrapper &&
            const DeepCollectionEquality().equals(other.values, v.values));
  }

  @override
  int get hashCode {
    final v = this as SetWrapper;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.values),
    );
  }

  @override
  String toString() {
    final v = this as SetWrapper;
    return 'SetWrapper{values: ${v.values}}';
  }
}

mixin ListWrapperData {
  static ListWrapper fromJson(Map<String, dynamic> json) {
    return ListWrapper(
      (json['values'] as List<dynamic>).map((e) => e as String).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as ListWrapper;
    return <String, dynamic>{
      'values': v.values,
    };
  }

  ListWrapper copyWith({
    List<String>? values,
  }) {
    final v = this as ListWrapper;
    return ListWrapper(
      values ?? v.values,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ListWrapper;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ListWrapper &&
            const DeepCollectionEquality().equals(other.values, v.values));
  }

  @override
  int get hashCode {
    final v = this as ListWrapper;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.values),
    );
  }

  @override
  String toString() {
    final v = this as ListWrapper;
    return 'ListWrapper{values: ${v.values}}';
  }
}

mixin MapWrapperData {
  static MapWrapper fromJson(Map<String, dynamic> json) {
    return MapWrapper(
      json['values'] as Map<String, dynamic>,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as MapWrapper;
    return <String, dynamic>{
      'values': v.values,
    };
  }

  MapWrapper copyWith({
    Map<String, dynamic>? values,
  }) {
    final v = this as MapWrapper;
    return MapWrapper(
      values ?? v.values,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as MapWrapper;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is MapWrapper &&
            const DeepCollectionEquality().equals(other.values, v.values));
  }

  @override
  int get hashCode {
    final v = this as MapWrapper;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.values),
    );
  }

  @override
  String toString() {
    final v = this as MapWrapper;
    return 'MapWrapper{values: ${v.values}}';
  }
}
