// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'function_fields_test.dart';

mixin Example1Data {
  static Example1 fromJson(Map<String, dynamic> json) {
    return Example1(
      functionField: json['functionField'] == null ? null : json['functionField'] as $c.int Function($c.int),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Example1;
    return <String, dynamic>{
      'functionField': ?v.functionField,
    };
  }

  Example1 copyWith({
    $c.int Function($c.int)? functionField,
  }) {
    final v = this as Example1;
    return Example1(
      functionField: functionField ?? v.functionField,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Example1;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Example1 &&
            (identical(other.functionField, v.functionField) || other.functionField == v.functionField));
  }

  @override
  int get hashCode {
    final v = this as Example1;
    return Object.hash(
      runtimeType,
      v.functionField,
    );
  }

  @override
  String toString() {
    final v = this as Example1;
    return 'Example1{functionField: ${v.functionField}}';
  }
}

mixin Example2Data {
  static Example2 fromJson(Map<String, dynamic> json) {
    return Example2(
      functionField: json['functionField'] == null
          ? null
          : json['functionField'] as $c.int Function($c.int, {$c.String? name}),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Example2;
    return <String, dynamic>{
      'functionField': ?v.functionField,
    };
  }

  Example2 copyWith({
    $c.int Function($c.int, {$c.String? name})? functionField,
  }) {
    final v = this as Example2;
    return Example2(
      functionField: functionField ?? v.functionField,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Example2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Example2 &&
            (identical(other.functionField, v.functionField) || other.functionField == v.functionField));
  }

  @override
  int get hashCode {
    final v = this as Example2;
    return Object.hash(
      runtimeType,
      v.functionField,
    );
  }

  @override
  String toString() {
    final v = this as Example2;
    return 'Example2{functionField: ${v.functionField}}';
  }
}

mixin Example3Data<T> {
  static Example3<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Example3<T>(
      functionField: json['functionField'] == null
          ? null
          : json['functionField'] as $c.int Function($c.int, {required T? data, $c.String? name}),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Example3<T>;
    return <String, dynamic>{
      'functionField': ?v.functionField,
    };
  }

  Example3<T> copyWith({
    $c.int Function($c.int, {required T? data, $c.String? name})? functionField,
  }) {
    final v = this as Example3<T>;
    return Example3<T>(
      functionField: functionField ?? v.functionField,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Example3<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Example3<T> &&
            (identical(other.functionField, v.functionField) || other.functionField == v.functionField));
  }

  @override
  int get hashCode {
    final v = this as Example3<T>;
    return Object.hash(
      runtimeType,
      v.functionField,
    );
  }

  @override
  String toString() {
    final v = this as Example3<T>;
    return 'Example3<$T>{functionField: ${v.functionField}}';
  }
}
