// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'food.dart';

mixin AppleData {
  static Apple fromJson(Map<String, dynamic> json) {
    return Apple(
      json['isRed'] as bool,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Apple;
    return <String, dynamic>{
      'isRed': v.isRed,
    };
  }

  Apple copyWith({
    bool? isRed,
  }) {
    final v = this as Apple;
    return Apple(
      isRed ?? v.isRed,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Apple;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Apple &&
            (identical(other.isRed, v.isRed) || other.isRed == v.isRed));
  }

  @override
  int get hashCode {
    final v = this as Apple;
    return Object.hash(
      runtimeType,
      v.isRed,
    );
  }

  @override
  String toString() {
    final v = this as Apple;
    return 'Apple{isRed: ${v.isRed}}';
  }
}

mixin BreadData {
  static Bread fromJson(Map<String, dynamic> json) {
    return Bread(
      (json['slices'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Bread;
    return <String, dynamic>{
      'slices': v.slices,
    };
  }

  Bread copyWith({
    int? slices,
  }) {
    final v = this as Bread;
    return Bread(
      slices ?? v.slices,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Bread;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Bread &&
            (identical(other.slices, v.slices) || other.slices == v.slices));
  }

  @override
  int get hashCode {
    final v = this as Bread;
    return Object.hash(
      runtimeType,
      v.slices,
    );
  }

  @override
  String toString() {
    final v = this as Bread;
    return 'Bread{slices: ${v.slices}}';
  }
}

mixin CakeData {
  static Cake fromJson(Map<String, dynamic> json) {
    return Cake(
      json['type'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Cake;
    return <String, dynamic>{
      'type': v.type,
    };
  }

  Cake copyWith({
    String? type,
  }) {
    final v = this as Cake;
    return Cake(
      type ?? v.type,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Cake;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is Cake && (identical(other.type, v.type) || other.type == v.type));
  }

  @override
  int get hashCode {
    final v = this as Cake;
    return Object.hash(
      runtimeType,
      v.type,
    );
  }

  @override
  String toString() {
    final v = this as Cake;
    return 'Cake{type: ${v.type}}';
  }
}
