// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'models.dart';

mixin PersonData {
  static Person fromJson(Map<String, dynamic> json) {
    return Person(
      json['firstName'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Person;
    return <String, dynamic>{
      'firstName': v.firstName,
    };
  }

  Person copyWith({
    String? firstName,
  }) {
    final v = this as Person;
    return Person(
      firstName ?? v.firstName,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Person;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Person &&
            (identical(other.firstName, v.firstName) || other.firstName == v.firstName));
  }

  @override
  int get hashCode {
    final v = this as Person;
    return Object.hash(
      runtimeType,
      v.firstName,
    );
  }

  @override
  String toString() {
    final v = this as Person;
    return 'Person{firstName: ${v.firstName}}';
  }
}
