// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'models.dart';

mixin PersonData {
  static Person fromJson(Map<String, dynamic> json) {
    return Person(
      json['firstName'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Person;
    return <String, dynamic>{
      'firstName': v.firstName,
    };
  }

  Person copyWith({
    String? firstName,
  }) {
    final v = this as Person;
    return Person(
      firstName ?? v.firstName,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Person;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Person &&
            (identical(other.firstName, v.firstName) || other.firstName == v.firstName));
  }

  @override
  int get hashCode {
    final v = this as Person;
    return Object.hash(
      runtimeType,
      v.firstName,
    );
  }

  @override
  String toString() {
    final v = this as Person;
    return 'Person{firstName: ${v.firstName}}';
  }
}
