// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of 'example5.dart';

mixin UserProfile5Data {
  static UserProfile5 fromJson(Map<String, dynamic> json) {
    return UserProfile5(
      name: json['UserName'] as String,
      age: (json['age'] as num?)?.toInt(),
      address: json['address'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile5;
    return <String, dynamic>{
      'UserName': v.name,
      'age': ?v.age,
      'address': ?v.address,
    };
  }

  UserProfile5 copyWith({
    String? name,
    Option<int> age = const Option.undefined(),
    String? address,
  }) {
    final v = this as UserProfile5;
    return UserProfile5(
      name: name ?? v.name,
      age: age.isUndefined ? v.age : age.casted(),
      address: address ?? v.address,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile5;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile5 &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.address, v.address) || other.address == v.address));
  }

  @override
  int get hashCode {
    final v = this as UserProfile5;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
      v.address,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile5;
    return 'UserProfile5{name: ${v.name}, age: ${v.age}, address: ${v.address}}';
  }
}

mixin UserProfile6Data {
  static UserProfile6 fromJson(Map<String, dynamic> json) {
    return UserProfile6(
      name: json['UserName'] as String,
      age: (json['age'] as num?)?.toInt(),
      address: json['address'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile6;
    return <String, dynamic>{
      'UserName': v.name,
      'age': ?v.age,
      'address': ?v.address,
    };
  }

  UserProfile6 copyWith({
    String? name,
    Option<int> age = const Option.undefined(),
    String? address,
  }) {
    final v = this as UserProfile6;
    return UserProfile6(
      name: name ?? v.name,
      age: age.isUndefined ? v.age : age.casted(),
      address: address ?? v.address,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile6;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile6 &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.address, v.address) || other.address == v.address));
  }

  @override
  int get hashCode {
    final v = this as UserProfile6;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
      v.address,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile6;
    return 'UserProfile6{name: ${v.name}, age: ${v.age}, address: ${v.address}}';
  }
}
