// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of 'example2.dart';

mixin UserProfileData {
  static UserProfile fromJson(Map<String, dynamic> json) {
    return UserProfile(
      username: json['username'] as String,
      email: json['email'] as String,
      age: (json['age'] as num?)?.toInt(),
      roles: (json['roles'] as List<dynamic>?)?.map((e) => e as String).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile;
    return <String, dynamic>{
      'username': v.username,
      'email': v.email,
      'age': ?v.age,
      'roles': ?v.roles,
    };
  }

  UserProfile copyWith({
    String? username,
    String? email,
    int? age,
    List<String>? roles,
  }) {
    final v = this as UserProfile;
    return UserProfile(
      username: username ?? v.username,
      email: email ?? v.email,
      age: age ?? v.age,
      roles: roles ?? v.roles,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile &&
            (identical(other.username, v.username) || other.username == v.username) &&
            (identical(other.email, v.email) || other.email == v.email) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            const DeepCollectionEquality().equals(other.roles, v.roles));
  }

  @override
  int get hashCode {
    final v = this as UserProfile;
    return Object.hash(
      runtimeType,
      v.username,
      v.email,
      v.age,
      const DeepCollectionEquality().hash(v.roles),
    );
  }

  @override
  String toString() {
    final v = this as UserProfile;
    return 'UserProfile{username: ${v.username}, email: ${v.email}, age: ${v.age}, roles: ${v.roles}}';
  }

  static Schema get schema {
    return S.object(
      title: 'UserProfile',
      description: 'Schema for UserProfile',
      required: ['username', 'email'],
      properties: {
        'username': S.string(
          description: 'Must be 3-20 characters, lowercase letters and numbers only.',
          minLength: 3,
          maxLength: 20,
          pattern: r'^[a-z0-9]+$',
        ),
        'email': S.string(
          description: 'A valid email address.',
          format: 'email',
        ),
        'age': S.integer(
          description: 'Optional age, must be 18 or older.',
          minimum: 18,
        ),
        'roles': S.list(
          description: 'Optional list of user roles, must be unique.',
          items: S.string(),
          uniqueItems: true,
        ),
      },
      additionalProperties: false,
    );
  }
}

mixin UserProfile2Data {
  static UserProfile2 fromJson(Map<String, dynamic> json) {
    return UserProfile2(
      username: json['username'] as String,
      email: json['email'] as String,
      age: (json['age'] as num?)?.toInt(),
      roles: (json['roles'] as List<dynamic>?)?.map((e) => e as String).toList(),
      customData: (json['CustomData'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile2;
    return <String, dynamic>{
      'username': v.username,
      'email': v.email,
      'age': ?v.age,
      'roles': ?v.roles,
      'CustomData': v.customData,
    };
  }

  UserProfile2 copyWith({
    String? username,
    String? email,
    int? age,
    List<String>? roles,
    int? customData,
  }) {
    final v = this as UserProfile2;
    return UserProfile2(
      username: username ?? v.username,
      email: email ?? v.email,
      age: age ?? v.age,
      roles: roles ?? v.roles,
      customData: customData ?? v.customData,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile2 &&
            (identical(other.username, v.username) || other.username == v.username) &&
            (identical(other.email, v.email) || other.email == v.email) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            const DeepCollectionEquality().equals(other.roles, v.roles) &&
            (identical(other.customData, v.customData) || other.customData == v.customData));
  }

  @override
  int get hashCode {
    final v = this as UserProfile2;
    return Object.hash(
      runtimeType,
      v.username,
      v.email,
      v.age,
      const DeepCollectionEquality().hash(v.roles),
      v.customData,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile2;
    return 'UserProfile2{username: ${v.username}, email: ${v.email}, age: ${v.age}, roles: ${v.roles}, customData: ${v.customData}}';
  }

  static Schema get schema {
    return S.object(
      title: 'UserProfile2',
      description: 'Schema for UserProfile2',
      required: ['username', 'email', 'CustomData'],
      properties: {
        'username': S.string(),
        'email': S.string(),
        'age': S.integer(),
        'roles': S.list(
          items: S.string(),
        ),
        'CustomData': S.integer(),
      },
      additionalProperties: false,
    );
  }
}
