// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of 'external_model.dart';

mixin WrappedData {
  static Wrapped fromJson(Map<String, dynamic> json) {
    return Wrapped(
      id: json['id'] as String,
      model: ExternalModel.fromJson(json['model'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Wrapped;
    return <String, dynamic>{
      'id': v.id,
      'model': ?Wrapped.toJsonExt(v.model),
    };
  }

  Wrapped copyWith({
    String? id,
    ExternalModel? model,
  }) {
    final v = this as Wrapped;
    return Wrapped(
      id: id ?? v.id,
      model: model ?? v.model,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Wrapped;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Wrapped &&
            (identical(other.id, v.id) || other.id == v.id) &&
            (identical(other.model, v.model) || other.model == v.model));
  }

  @override
  int get hashCode {
    final v = this as Wrapped;
    return Object.hash(
      runtimeType,
      v.id,
      v.model,
    );
  }

  @override
  String toString() {
    final v = this as Wrapped;
    return 'Wrapped{id: ${v.id}, model: ${v.model}}';
  }
}

mixin Wrapped2Data {
  static Wrapped2 fromJson(Map<String, dynamic> json) {
    return Wrapped2(
      id: json['id'] as String,
      model: ExternalModel2.fromJson(json['model'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Wrapped2;
    return <String, dynamic>{
      'id': v.id,
      'model': ?Wrapped2.toJsonExt(v.model),
    };
  }

  Wrapped2 copyWith({
    String? id,
    ExternalModel2<String>? model,
  }) {
    final v = this as Wrapped2;
    return Wrapped2(
      id: id ?? v.id,
      model: model ?? v.model,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Wrapped2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Wrapped2 &&
            (identical(other.id, v.id) || other.id == v.id) &&
            (identical(other.model, v.model) || other.model == v.model));
  }

  @override
  int get hashCode {
    final v = this as Wrapped2;
    return Object.hash(
      runtimeType,
      v.id,
      v.model,
    );
  }

  @override
  String toString() {
    final v = this as Wrapped2;
    return 'Wrapped2{id: ${v.id}, model: ${v.model}}';
  }
}
