// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'main.dart';

mixin _MyHomePageStateForm {
  // Value notifiers for form fields
  final nameState = ValueNotifier(Optional<String>.undefined());
  final ageState = ValueNotifier(Optional<int>.undefined());
  final profileState = ValueNotifier(Optional<UserProfile2>.undefined());
  final myListState = ValueNotifier(Optional<List<String>>.value(['a', 'b', 'c']));

  // Getters and setters for form fields
  String? get name {
    final opt = nameState.value;
    return opt.isSet ? opt.value : null;
  }

  set name(String? value) {
    if (value == null) {
      nameState.value = Optional<String>.nullValue();
    } else {
      nameState.value = Optional<String>.value(value);
    }
  }

  int? get age {
    final opt = ageState.value;
    return opt.isSet ? opt.value : null;
  }

  set age(int? value) {
    if (value == null) {
      ageState.value = Optional<int>.nullValue();
    } else {
      ageState.value = Optional<int>.value(value);
    }
  }

  UserProfile2? get profile {
    final opt = profileState.value;
    return opt.isSet ? opt.value : null;
  }

  set profile(UserProfile2? value) {
    if (value == null) {
      profileState.value = Optional<UserProfile2>.nullValue();
    } else {
      profileState.value = Optional<UserProfile2>.value(value);
    }
  }

  List<String>? get myList {
    final opt = myListState.value;
    return opt.isSet ? opt.value : null;
  }

  set myList(List<String>? value) {
    if (value == null) {
      myListState.value = Optional<List<String>>.nullValue();
    } else {
      myListState.value = Optional<List<String>>.value(value);
    }
  }

  Future<Map<String, List<ValidationError>>> validate() async {
    final state = this as _MyHomePageState;
    final formState = <String, List<ValidationError>>{};
    const fieldNames = ['name', 'age', 'profile', 'myList'];
    try {
      final result = await Future.wait([
        state.nameSchema.validate(nameState.value.value),
        state.ageSchema.validate(ageState.value.value),
        state.profileSchema.validate(profileState.value.value),
        state.myListSchema.validate(myListState.value.value),
      ]);

      for (int i = 0; i < fieldNames.length; i++) {
        if (result[i].isNotEmpty) {
          formState[fieldNames[i]] = result[i];
        }
      }
    } catch (e) {
      formState['__form__'] = [
        ValidationError(ValidationErrorType.custom, path: const [], details: 'Validation failed: ${e.toString()}'),
      ];
    }
    return formState;
  }

  // Dispose all value notifiers
  void dispose() {
    nameState.dispose();
    ageState.dispose();
    profileState.dispose();
    myListState.dispose();
  }
}
