// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'simple.dart';

mixin UserProfileData {
  static UserProfile fromJson(Map<String, dynamic> json) {
    return UserProfile(
      name: json['UserName'] as String,
      age: (json['age'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile;
    return <String, dynamic>{
      'UserName': v.name,
      'age': v.age,
    };
  }

  UserProfile copyWith({
    String? name,
    int? age,
  }) {
    final v = this as UserProfile;
    return UserProfile(
      name: name ?? v.name,
      age: age ?? v.age,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age));
  }

  @override
  int get hashCode {
    final v = this as UserProfile;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile;
    return 'UserProfile{name: ${v.name}, age: ${v.age}}';
  }
}

mixin AnimalData {
  static Animal fromJson(Map<String, dynamic> json) {
    final type = json['type'];
    return switch (type) {
      'Cat' => CatData.fromJson(json),
      _ when Dog.checkIsDog(json) => DogData.fromJson(json),
      _ => throw InvalidDiscriminatorException(
        'Unrecognized discriminator value "$type" for Animal. No default subtype is defined.',
      ),
    };
  }

  Map<String, dynamic> toJsonBy() {
    return switch (this) {
      Cat v => v.toJson(),
      Dog v => v.toJson(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res map<Res>({
    required Res Function(Cat value) cat,
    required Res Function(Dog value) dog,
    Res Function(Animal value)? fallback,
  }) {
    return switch (this) {
      Cat v => cat(v),
      Dog v => dog(v),
      _ when fallback != null => fallback(this as Animal),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  Res? mapOrNull<Res>({
    Res? Function(Cat value)? cat,
    Res? Function(Dog value)? dog,
  }) {
    return switch (this) {
      Cat v => cat?.call(v),
      Dog v => dog?.call(v),
      _ => null,
    };
  }

  Animal copyWithBy({
    Cat Function(Cat value)? cat,
    Dog Function(Dog value)? dog,
  }) {
    return switch (this) {
      Cat v => cat != null ? cat(v) : v.copyWith(),
      Dog v => dog != null ? dog(v) : v.copyWith(),
      _ => throw InvalidDiscriminatorException('Unrecognized discriminator value "$runtimeType" for Animal.'),
    };
  }

  @pragma('vm:prefer-inline')
  Cat asCat() {
    return this as Cat;
  }

  @pragma('vm:prefer-inline')
  Dog asDog() {
    return this as Dog;
  }
}

mixin CatData {
  static Cat fromJson(Map<String, dynamic> json) {
    return Cat(
      name: json['name'] as String,
      nickName: json['nickName'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Cat;
    return <String, dynamic>{
      'name': v.name,
      'nickName': v.nickName,
      'type': 'Cat',
    };
  }

  Cat copyWith({
    String? name,
    String? nickName,
  }) {
    final v = this as Cat;
    return Cat(
      name: name ?? v.name,
      nickName: nickName ?? v.nickName,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Cat;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Cat &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.nickName, v.nickName) || other.nickName == v.nickName));
  }

  @override
  int get hashCode {
    final v = this as Cat;
    return Object.hash(
      runtimeType,
      v.name,
      v.nickName,
    );
  }

  @override
  String toString() {
    final v = this as Cat;
    return 'Cat{name: ${v.name}, nickName: ${v.nickName}}';
  }
}

mixin DogData {
  static Dog fromJson(Map<String, dynamic> json) {
    return Dog(
      name: json['name'] as String,
      big: json['big'] as bool,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Dog;
    return <String, dynamic>{
      'name': v.name,
      'big': v.big,
    };
  }

  Dog copyWith({
    String? name,
    bool? big,
  }) {
    final v = this as Dog;
    return Dog(
      name: name ?? v.name,
      big: big ?? v.big,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Dog;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Dog &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.big, v.big) || other.big == v.big));
  }

  @override
  int get hashCode {
    final v = this as Dog;
    return Object.hash(
      runtimeType,
      v.name,
      v.big,
    );
  }

  @override
  String toString() {
    final v = this as Dog;
    return 'Dog{name: ${v.name}, big: ${v.big}}';
  }
}

mixin UserProfile2Data {
  static UserProfile2 fromJson(Map<String, dynamic> json) {
    return UserProfile2(
      name: json['UserName'] as String,
      age: (json['age'] as num?)?.toInt(),
      address: json['address'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile2;
    return <String, dynamic>{
      'UserName': v.name,
      'age': ?v.age,
      'address': ?v.address,
    };
  }

  UserProfile2 copyWith({
    String? name,
    Option<int> age = const Option.undefined(),
    String? address,
  }) {
    final v = this as UserProfile2;
    return UserProfile2(
      name: name ?? v.name,
      age: age.isUndefined ? v.age : age.casted(),
      address: address ?? v.address,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile2 &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.address, v.address) || other.address == v.address));
  }

  @override
  int get hashCode {
    final v = this as UserProfile2;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
      v.address,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile2;
    return 'UserProfile2{name: ${v.name}, age: ${v.age}, address: ${v.address}}';
  }
}

mixin UserProfile3Data {
  static UserProfile3 fromJson(Map<String, dynamic> json) {
    return UserProfile3(
      name: json['UserName'] as String,
      age: (json['age'] as num?)?.toInt(),
      address: json['address'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as UserProfile3;
    return <String, dynamic>{
      'UserName': v.name,
      'age': ?v.age,
      'address': ?v.address,
    };
  }

  UserProfile3 copyWith({
    String? name,
    Option<int> age = const Option.undefined(),
    String? address,
  }) {
    final v = this as UserProfile3;
    return UserProfile3(
      name: name ?? v.name,
      age: age.isUndefined ? v.age : age.casted(),
      address: address ?? v.address,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as UserProfile3;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is UserProfile3 &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.address, v.address) || other.address == v.address));
  }

  @override
  int get hashCode {
    final v = this as UserProfile3;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
      v.address,
    );
  }

  @override
  String toString() {
    final v = this as UserProfile3;
    return 'UserProfile3{name: ${v.name}, age: ${v.age}, address: ${v.address}}';
  }
}
