// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: invalid_use_of_internal_member, unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

import 'dart:typed_data';

import 'package:macro_kit/macro_kit.dart';

import 'images/flutter.dart' as i3356018501;
import 'images/dart.dart' as i3657187921;
import './butterfly.dart' as i2123351816;

final class EmbedFS {
  EmbedFS._();
  
  static final _EmbedRegistryImpl _registry = _EmbedRegistryImpl._();
  
  static EmbedFile file(String path) => EmbedFile(path)..$registry = _registry;
  
  static EmbedDirectory directory(String path) => EmbedDirectory(path)..$registry = _registry;
  
  static EmbedDirectory get current => directory('/');
}    
    
final class _EmbedRegistryImpl implements EmbedRegistry {   
  _EmbedRegistryImpl._();
   
  final cache = <String, Uint8List>{};

  void clearCache() => cache.clear();

  List<String> get allPaths => _files.keys.toList();

  bool exists(String path) => _files.containsKey(path);

  Uint8List? readBytes(String path) => _files[path]?.call();

  final Map<String, Uint8List Function()> _files = {
    '/assets/images/flutter.jpg': () => i3356018501.flutterData,
    '/assets/images/dart.svg': () => i3657187921.dartData,
    '/assets/butterfly.jpg': () => i2123351816.butterflyData,
  };

}
