// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'as_literal_test.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      a: json['a'] as GeoPoint,
      b: json['b'] as GeoPoint?,
      c:
          json['c'] as GeoPoint? ??
          const GeoPoint(
            1.0,
            1.0,
          ),
      d:
          json['d'] as GeoPoint? ??
          const GeoPoint(
            2.0,
            2.0,
          ),
      e: A.geoPointFromJson(json['e'] as Map<String, dynamic>),
      f: json['f'] as CustomGeoPoint,
      g: A.asLiteralFromToJson(json['g'] as dynamic),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': ?v.b,
      'c': ?v.c,
      'd': v.d,
      'e': A.geoPointToJson(v.e),
      'f': v.f,
      'g': A.asLiteralFromToJson(v.g),
    };
  }

  A copyWith({
    GeoPoint? a,
    GeoPoint? b,
    GeoPoint? c,
    GeoPoint? d,
    GeoPoint? e,
    CustomGeoPoint? f,
    CustomGeoPoint? g,
  }) {
    final v = this as A;
    return A(
      a: a ?? v.a,
      b: b ?? v.b,
      c: c ?? v.c,
      d: d ?? v.d,
      e: e ?? v.e,
      f: f ?? v.f,
      g: g ?? v.g,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.c, v.c) || other.c == v.c) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.e, v.e) || other.e == v.e) &&
            (identical(other.f, v.f) || other.f == v.f) &&
            (identical(other.g, v.g) || other.g == v.g));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.c,
      v.d,
      v.e,
      v.f,
      v.g,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}, c: ${v.c}, d: ${v.d}, e: ${v.e}, f: ${v.f}, g: ${v.g}}';
  }
}
