// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'basic_serialization.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      json['a'] as String,
      b: (json['b'] as num?)?.toInt() ?? 0,
      c: (json['c'] as num?)?.toDouble(),
      d: json['d'] as bool,
      e: MacroExt.decodeNullableEnum(B.values, json['e'], unknownValue: null),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'c': ?v.c,
      'd': v.d,
      'e': ?v.e?.name,
    };
  }

  A copyWith({
    String? a,
    int? b,
    double? c,
    bool? d,
    B? e,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
      b: b ?? v.b,
      c: c ?? v.c,
      d: d ?? v.d,
      e: e ?? v.e,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.c, v.c) || other.c == v.c) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.e, v.e) || other.e == v.e));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.c,
      v.d,
      v.e,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}, c: ${v.c}, d: ${v.d}, e: ${v.e}}';
  }
}
