// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'encoding_params_test.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      json['a'] as String,
      b: MacroExt.decodeNullableEnum(B.values, json['b'], unknownValue: null),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': ?v.b?.name,
    };
  }

  A copyWith({
    String? a,
    B? b,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
      b: b ?? v.b,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}}';
  }
}
