// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'named_ctor_serialization_test.dart';

mixin CData {
  static C fromJson(Map<String, dynamic> json) {
    return C(
      (json['x'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as C;
    return <String, dynamic>{
      'x': v.x,
    };
  }

  C copyWith({
    int? x,
  }) {
    final v = this as C;
    return C(
      x ?? v.x,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as C;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is C && (identical(other.x, v.x) || other.x == v.x));
  }

  @override
  int get hashCode {
    final v = this as C;
    return Object.hash(
      runtimeType,
      v.x,
    );
  }

  @override
  String toString() {
    final v = this as C;
    return 'C{x: ${v.x}}';
  }
}

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      (json['a'] as num).toInt(),
      (json['b'] as num).toInt(),
      CData.fromJson(json['c'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'c': v.c.toJson(),
    };
  }

  A copyWith({
    int? a,
    int? b,
    C? c,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
      b ?? v.b,
      c ?? v.c,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.c, v.c) || other.c == v.c));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.c,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}, c: ${v.c}}';
  }
}

mixin A2Data {
  static A2 fromJson(Map<String, dynamic> json) {
    return A2.filled(
      (json['a'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A2;
    return <String, dynamic>{
      'a': v.a,
    };
  }

  A2 copyWith({
    int? a,
  }) {
    final v = this as A2;
    return A2.filled(
      a ?? v.a,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is A2 && (identical(other.a, v.a) || other.a == v.a));
  }

  @override
  int get hashCode {
    final v = this as A2;
    return Object.hash(
      runtimeType,
      v.a,
    );
  }

  @override
  String toString() {
    final v = this as A2;
    return 'A2{a: ${v.a}}';
  }
}

mixin BData {
  static B fromJson(Map<String, dynamic> json) {
    return B(
      (json['a'] as num).toInt(),
      (json['b'] as num).toInt(),
      (json['d'] as num).toInt(),
      CData.fromJson(json['c'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'd': v.d,
      'c': v.c.toJson(),
    };
  }

  B copyWith({
    int? a,
    int? b,
    int? d,
    C? c,
  }) {
    final v = this as B;
    return B(
      a ?? v.a,
      b ?? v.b,
      d ?? v.d,
      c ?? v.c,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.d, v.d) || other.d == v.d) &&
            (identical(other.c, v.c) || other.c == v.c));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v.d,
      v.c,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{a: ${v.a}, b: ${v.b}, d: ${v.d}, c: ${v.c}}';
  }
}
