// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'nested_serialization_test.dart';

mixin CarData {
  static Car fromJson(Map<String, dynamic> json) {
    return Car(
      (json['drivenKm'] as num).toInt(),
      MacroExt.decodeEnum(Brand.values, json['brand'], unknownValue: null),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Car;
    return <String, dynamic>{
      'drivenKm': v.drivenKm,
      'brand': v.brand.name,
    };
  }

  Car copyWith({
    int? drivenKm,
    Brand? brand,
  }) {
    final v = this as Car;
    return Car(
      drivenKm ?? v.drivenKm,
      brand ?? v.brand,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Car;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Car &&
            (identical(other.drivenKm, v.drivenKm) || other.drivenKm == v.drivenKm) &&
            (identical(other.brand, v.brand) || other.brand == v.brand));
  }

  @override
  int get hashCode {
    final v = this as Car;
    return Object.hash(
      runtimeType,
      v.drivenKm,
      v.brand,
    );
  }

  @override
  String toString() {
    final v = this as Car;
    return 'Car{drivenKm: ${v.drivenKm}, brand: ${v.brand}}';
  }
}

mixin PersonData {
  static Person fromJson(Map<String, dynamic> json) {
    return Person(
      json['name'] as String,
      age: (json['age'] as num?)?.toInt() ?? 18,
      car: json['car'] == null ? null : CarData.fromJson(json['car'] as Map<String, dynamic>),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Person;
    return <String, dynamic>{
      'name': v.name,
      'age': v.age,
      'car': ?v.car?.toJson(),
    };
  }

  Person copyWith({
    String? name,
    int? age,
    Car? car,
  }) {
    final v = this as Person;
    return Person(
      name ?? v.name,
      age: age ?? v.age,
      car: car ?? v.car,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Person;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Person &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.car, v.car) || other.car == v.car));
  }

  @override
  int get hashCode {
    final v = this as Person;
    return Object.hash(
      runtimeType,
      v.name,
      v.age,
      v.car,
    );
  }

  @override
  String toString() {
    final v = this as Person;
    return 'Person{name: ${v.name}, age: ${v.age}, car: ${v.car}}';
  }
}
