// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'param_rewrite_test.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      (json['a'] as num).toInt(),
      (json['b'] as num?)?.toInt(),
      (json['c'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
      'b': v.b,
      'c': v._c,
    };
  }

  A copyWith({
    int? a,
    int? b,
    int? c,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
      b ?? v.b,
      c ?? v._c,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A &&
            (identical(other.a, v.a) || other.a == v.a) &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other._c, v._c) || other._c == v._c));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.a,
      v.b,
      v._c,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{a: ${v.a}, b: ${v.b}, c: ${v._c}}';
  }
}

mixin BData {
  static B fromJson(Map<String, dynamic> json) {
    return B(
      (json['a'] as num).toInt(),
      (json['b'] as num).toInt(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B;
    return <String, dynamic>{
      'a': v.b,
      'b': v.a,
    };
  }

  B copyWith({
    int? b,
    int? a,
  }) {
    final v = this as B;
    return B(
      b ?? v.b,
      a ?? v.a,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B &&
            (identical(other.b, v.b) || other.b == v.b) &&
            (identical(other.a, v.a) || other.a == v.a));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.b,
      v.a,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{a: ${v.b}, b: ${v.a}}';
  }
}

mixin CData {
  static C fromJson(Map<String, dynamic> json) {
    return C(
      json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as C;
    return <String, dynamic>{
      'name': v.name,
    };
  }

  C copyWith({
    String? name,
  }) {
    final v = this as C;
    return C(
      name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as C;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is C && (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as C;
    return Object.hash(
      runtimeType,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as C;
    return 'C{name: ${v.name}}';
  }
}
