// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'compute_all_test.dart';

const __stringValMacro_computeHash = 2218081105;
const stringVal = 'hello world';

const __intValMacro_computeHash = 2218081105;
const intVal = 42;

const __doubleValMacro_computeHash = 2218081105;
const doubleVal = 3.14;

const __boolValMacro_computeHash = 2218081105;
const boolVal = true;

const __nullValMacro_computeHash = 2218081105;
const nullVal = null;

const __negativeIntMacro_computeHash = 2218081105;
const negativeInt = -100;

const __zeroValMacro_computeHash = 2218081105;
const zeroVal = 0;

const __emptyStringMacro_computeHash = 2218081105;
const emptyString = '';

const __interpolationMacro_computeHash = 2218081105;
const interpolation = 'year=2026';

const __concatMacro_computeHash = 2218081105;
const concat = 'foobar';

const __blockBodyMacro_computeHash = 2218081105;
const blockBody = 30;

const __blockBodyStringMacro_computeHash = 2218081105;
const blockBodyString = 'a-b-c';

const __listValMacro_computeHash = 2218081105;
const listVal = [1, 2, 3];

const __mapValMacro_computeHash = 2218081105;
const mapVal = {'a': 1, 'b': 2};

const __nestedListMacro_computeHash = 2218081105;
const nestedList = [
  [1, 2],
  [3, 4],
];

const __nestedMapMacro_computeHash = 2218081105;
const nestedMap = {
  'users': {'alice': 1, 'bob': 2},
};

const __dartCodeSimpleMacro_computeHash = 2218081105;
const dartCodeSimple = 2 | 10;

const __dartCodeExprMacro_computeHash = 2218081105;
const dartCodeExpr = Duration(seconds: 300);

const __encodeStringMacro_computeHash = 2218081105;
const encodeString = 'HELLO';

const __encodeIntMacro_computeHash = 2218081105;
const encodeInt = 84;

const __depsSameFileMacro_computeHash = 950100574;
const depsSameFile = 'MyApp v2.1.0';

const __depsFuncMacro_computeHash = 1992698252;
const depsFunc = 'App-1.0';

const __depsMultiMacro_computeHash = 19184522;
const depsMulti = 'retries=3, timeout=5000';

const __dartCodeBypassMacro_computeHash = 2218081105;
const dartCodeBypass = Color(0xFF00007b);

const __randomMacro_computeHash = 2218081105;
const random = 47577;

const __tagCountMacro_computeHash = 275753531;
const tagCount = 3;

const __ternaryMacro_computeHash = 2218081105;
const ternary = 'yes';

const __largeStringMacro_computeHash = 2218081105;
const largeString =
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';

const __mathMacro_computeHash = 2218081105;
const math = 12;

const __stringOpsMacro_computeHash = 2218081105;
const stringOps = 5;
