// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'computed_test.dart';

mixin TestData {
  static Test fromJson(Map<String, dynamic> json) {
    return Test(
      id: json['id'] as String,
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Test;
    return <String, dynamic>{
      'id': v.id,
      'name': v.name,
    };
  }

  Test copyWith({
    String? id,
    String? name,
  }) {
    final v = this as Test;
    return Test(
      id: id ?? v.id,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Test;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Test &&
            (identical(other.id, v.id) || other.id == v.id) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Test;
    return Object.hash(
      runtimeType,
      v.id,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Test;
    return 'Test{id: ${v.id}, name: ${v.name}}';
  }
}

const _versionMacroHash = 3860371886;
const version = '2';
