// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'computed_test.dart';

mixin TestData {
  static Test fromJson(Map<String, dynamic> json) {
    return Test(
      id: json['id'] as String,
      name: json['name'] as String,
      name2: json['name2'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Test;
    return <String, dynamic>{
      'id': v.id,
      'name': v.name,
      'name2': v.name2,
    };
  }

  Test copyWith({
    String? id,
    String? name,
    String? name2,
  }) {
    final v = this as Test;
    return Test(
      id: id ?? v.id,
      name: name ?? v.name,
      name2: name2 ?? v.name2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Test;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Test &&
            (identical(other.id, v.id) || other.id == v.id) &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.name2, v.name2) || other.name2 == v.name2));
  }

  @override
  int get hashCode {
    final v = this as Test;
    return Object.hash(
      runtimeType,
      v.id,
      v.name,
      v.name2,
    );
  }

  @override
  String toString() {
    final v = this as Test;
    return 'Test{id: ${v.id}, name: ${v.name}, name2: ${v.name2}}';
  }
}

dynamic _processResult<T>(T raw, [String Function(T)? enc, String Function(String)? dec]) {
  if (raw case DartCode raw) return {'__dartCode__': raw.code};
  if (enc == null && dec == null) return raw;
  final String encoded = enc != null ? enc(raw).toString() : raw.toString();
  return dec != null ? dec(encoded) : encoded;
}

void computeRunner() async {
  final resultFile = File('/Volumes/Projects/Server/swiftybase/macro/test/computed/computed_test_compute_3547781247.g.dart.result')..createSync(recursive: true);
  try {
    final results = <String, dynamic>{};
    results['versionMacro'] = _processResult(await versionMacro.call());
    resultFile.writeAsStringSync(jsonEncode({'type': 'value', 'data': results}));
  } catch (e, s) {
    resultFile.writeAsStringSync(jsonEncode({'type': 'error', 'message': e.toString(), 'stackTrace': s.toString()}));
  }
}

const _versionMacro_computeHash = 2259548781;
const version = '1';
