// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'extends_basic_test.dart';

mixin AData {
  static A fromJson(Map<String, dynamic> json) {
    return A(
      json['data'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'data': v.data,
    };
  }

  A copyWith({
    String? data,
  }) {
    final v = this as A;
    return A(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is A && (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as A;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as A;
    return 'A{data: ${v.data}}';
  }
}

mixin BData {
  static B fromJson(Map<String, dynamic> json) {
    return B(
      json['data'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B;
    return <String, dynamic>{
      'data': v.data,
    };
  }

  B copyWith({
    String? data,
  }) {
    final v = this as B;
    return B(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is B && (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{data: ${v.data}}';
  }
}

mixin A1Data {
  static A1 fromJson(Map<String, dynamic> json) {
    return A1(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A1;
    return <String, dynamic>{
      'data': ?v.data,
    };
  }

  A1 copyWith({
    String? data,
  }) {
    final v = this as A1;
    return A1(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A1;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is A1 && (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as A1;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as A1;
    return 'A1{data: ${v.data}}';
  }
}

mixin B1Data {
  static B1 fromJson(Map<String, dynamic> json) {
    return B1(
      json['custom'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B1;
    return <String, dynamic>{
      'custom': ?v.data,
    };
  }

  B1 copyWith({
    String? data,
  }) {
    final v = this as B1;
    return B1(
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B1;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is B1 && (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as B1;
    return Object.hash(
      runtimeType,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as B1;
    return 'B1{data: ${v.data}}';
  }
}

mixin A2Data {
  static A2 fromJson(Map<String, dynamic> json) {
    return A2(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A2;
    return <String, dynamic>{
      'data': v.dataVar,
    };
  }

  A2 copyWith({
    String? dataVar,
  }) {
    final v = this as A2;
    return A2(
      dataVar ?? v.dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A2 &&
            (identical(other.dataVar, v.dataVar) || other.dataVar == v.dataVar));
  }

  @override
  int get hashCode {
    final v = this as A2;
    return Object.hash(
      runtimeType,
      v.dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A2;
    return 'A2{data: ${v.dataVar}}';
  }
}

mixin B2Data {
  static B2 fromJson(Map<String, dynamic> json) {
    return B2(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B2;
    return <String, dynamic>{
      'data': v.dataVar,
    };
  }

  B2 copyWith({
    String? dataVar,
  }) {
    final v = this as B2;
    return B2(
      dataVar ?? v.dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B2;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B2 &&
            (identical(other.dataVar, v.dataVar) || other.dataVar == v.dataVar));
  }

  @override
  int get hashCode {
    final v = this as B2;
    return Object.hash(
      runtimeType,
      v.dataVar,
    );
  }

  @override
  String toString() {
    final v = this as B2;
    return 'B2{data: ${v.dataVar}}';
  }
}

mixin A3Data {
  static A3 fromJson(Map<String, dynamic> json) {
    return A3(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A3;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  A3 copyWith({
    String? data,
  }) {
    final v = this as A3;
    return A3(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A3;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A3 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as A3;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A3;
    return 'A3{data: ${v._dataVar}}';
  }
}

mixin B3Data {
  static B3 fromJson(Map<String, dynamic> json) {
    return B3(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B3;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  B3 copyWith({
    String? data,
  }) {
    final v = this as B3;
    return B3(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B3;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B3 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as B3;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as B3;
    return 'B3{data: ${v._dataVar}}';
  }
}

mixin A4Data {
  static A4 fromJson(Map<String, dynamic> json) {
    return A4.aa(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A4;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  A4 copyWith({
    String? data,
  }) {
    final v = this as A4;
    return A4.aa(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A4;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A4 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as A4;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A4;
    return 'A4{data: ${v._dataVar}}';
  }
}

mixin B4Data {
  static B4 fromJson(Map<String, dynamic> json) {
    return B4.bb(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B4;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  B4 copyWith({
    String? data,
  }) {
    final v = this as B4;
    return B4.bb(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B4;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B4 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as B4;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as B4;
    return 'B4{data: ${v._dataVar}}';
  }
}

mixin A5Data {
  static A5 fromJson(Map<String, dynamic> json) {
    return A5.aa(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A5;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  A5 copyWith({
    String? data,
  }) {
    final v = this as A5;
    return A5.aa(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A5;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A5 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as A5;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A5;
    return 'A5{data: ${v._dataVar}}';
  }
}

mixin B5Data {
  static B5 fromJson(Map<String, dynamic> json) {
    return B5(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B5;
    return <String, dynamic>{
      'data': v._dataVar,
    };
  }

  B5 copyWith({
    String? data,
  }) {
    final v = this as B5;
    return B5(
      data ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B5;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B5 &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as B5;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as B5;
    return 'B5{data: ${v._dataVar}}';
  }
}

mixin A6Data {
  static A6 fromJson(Map<String, dynamic> json) {
    return A6.aa(
      json['data'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as A6;
    return <String, dynamic>{
      'data': v.dataVar,
    };
  }

  A6 copyWith({
    String? dataVar,
  }) {
    final v = this as A6;
    return A6.aa(
      dataVar ?? v.dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A6;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A6 &&
            (identical(other.dataVar, v.dataVar) || other.dataVar == v.dataVar));
  }

  @override
  int get hashCode {
    final v = this as A6;
    return Object.hash(
      runtimeType,
      v.dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A6;
    return 'A6{data: ${v.dataVar}}';
  }
}

mixin B6Data {
  static B6 fromJson(Map<String, dynamic> json) {
    return B6(
      json['dataValue'] as String?,
      json['a2'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as B6;
    return <String, dynamic>{
      'dataValue': v.dataVar,
      'a2': v.a2,
    };
  }

  B6 copyWith({
    String? dataVar,
    String? a2,
  }) {
    final v = this as B6;
    return B6(
      dataVar ?? v.dataVar,
      a2 ?? v.a2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B6;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B6 &&
            (identical(other.dataVar, v.dataVar) || other.dataVar == v.dataVar) &&
            (identical(other.a2, v.a2) || other.a2 == v.a2));
  }

  @override
  int get hashCode {
    final v = this as B6;
    return Object.hash(
      runtimeType,
      v.dataVar,
      v.a2,
    );
  }

  @override
  String toString() {
    final v = this as B6;
    return 'B6{dataValue: ${v.dataVar}, a2: ${v.a2}}';
  }
}

mixin ANormalData<T> {
  static ANormal<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return ANormal<T>(
      json['name'] as String,
      fromJsonT(json['data']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as ANormal<T>;
    return <String, dynamic>{
      'name': v.name,
      'data': toJsonT(v.data),
    };
  }

  ANormal<T> copyWith({
    String? name,
    T? data,
  }) {
    final v = this as ANormal<T>;
    return ANormal<T>(
      name ?? v.name,
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ANormal<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ANormal<T> &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as ANormal<T>;
    return Object.hash(
      runtimeType,
      v.name,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as ANormal<T>;
    return 'ANormal<$T>{name: ${v.name}, data: ${v.data}}';
  }
}

mixin BNormalData<T> {
  static BNormal<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return BNormal<T>(
      json['name'] as String,
      fromJsonT(json['data']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as BNormal<T>;
    return <String, dynamic>{
      'name': v.name,
      'data': toJsonT(v.data),
    };
  }

  BNormal<T> copyWith({
    String? name,
    T? data,
  }) {
    final v = this as BNormal<T>;
    return BNormal<T>(
      name ?? v.name,
      data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as BNormal<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is BNormal<T> &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as BNormal<T>;
    return Object.hash(
      runtimeType,
      v.name,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as BNormal<T>;
    return 'BNormal<$T>{name: ${v.name}, data: ${v.data}}';
  }
}

mixin ANormal1Data<T> {
  static ANormal1<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return ANormal1<T>(
      name: json['name'] as String,
      data: fromJsonT(json['data']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as ANormal1<T>;
    return <String, dynamic>{
      'name': v.name,
      'data': toJsonT(v.data),
    };
  }

  ANormal1<T> copyWith({
    String? name,
    T? data,
  }) {
    final v = this as ANormal1<T>;
    return ANormal1<T>(
      name: name ?? v.name,
      data: data ?? v.data,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ANormal1<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ANormal1<T> &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.data, v.data) || other.data == v.data));
  }

  @override
  int get hashCode {
    final v = this as ANormal1<T>;
    return Object.hash(
      runtimeType,
      v.name,
      v.data,
    );
  }

  @override
  String toString() {
    final v = this as ANormal1<T>;
    return 'ANormal1<$T>{name: ${v.name}, data: ${v.data}}';
  }
}

mixin BNormal1Data<T> {
  static BNormal1<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return BNormal1<T>(
      data: fromJsonT(json['data']),
      name: json['name'] as String? ?? 'Rebaz',
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as BNormal1<T>;
    return <String, dynamic>{
      'data': toJsonT(v.data),
      'name': v.name,
    };
  }

  BNormal1<T> copyWith({
    T? data,
    String? name,
  }) {
    final v = this as BNormal1<T>;
    return BNormal1<T>(
      data: data ?? v.data,
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as BNormal1<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is BNormal1<T> &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as BNormal1<T>;
    return Object.hash(
      runtimeType,
      v.data,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as BNormal1<T>;
    return 'BNormal1<$T>{data: ${v.data}, name: ${v.name}}';
  }
}

mixin A7Data<T> {
  static A7<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return A7<T>(
      json['data'] as String,
      fromJsonT(json['gen']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as A7<T>;
    return <String, dynamic>{
      'data': v.data,
      'gen': toJsonT(v.gen),
    };
  }

  A7<T> copyWith({
    String? data,
    T? gen,
  }) {
    final v = this as A7<T>;
    return A7<T>(
      data ?? v.data,
      gen ?? v.gen,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A7<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A7<T> &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.gen, v.gen) || other.gen == v.gen));
  }

  @override
  int get hashCode {
    final v = this as A7<T>;
    return Object.hash(
      runtimeType,
      v.data,
      v.gen,
    );
  }

  @override
  String toString() {
    final v = this as A7<T>;
    return 'A7<$T>{data: ${v.data}, gen: ${v.gen}}';
  }
}

mixin B7Data<T> {
  static B7<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return B7<T>(
      json['data'] as String,
      fromJsonT(json['gen']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as B7<T>;
    return <String, dynamic>{
      'data': v.data,
      'gen': toJsonT(v.gen),
    };
  }

  B7<T> copyWith({
    String? data,
    T? gen,
  }) {
    final v = this as B7<T>;
    return B7<T>(
      data ?? v.data,
      gen ?? v.gen,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B7<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B7<T> &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.gen, v.gen) || other.gen == v.gen));
  }

  @override
  int get hashCode {
    final v = this as B7<T>;
    return Object.hash(
      runtimeType,
      v.data,
      v.gen,
    );
  }

  @override
  String toString() {
    final v = this as B7<T>;
    return 'B7<$T>{data: ${v.data}, gen: ${v.gen}}';
  }
}

mixin A8Data<T> {
  static A8<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return A8<T>.aa(
      fromJsonT(json['data2']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as A8<T>;
    return <String, dynamic>{
      'data2': toJsonT(v._dataVar),
    };
  }

  A8<T> copyWith({
    T? data2,
  }) {
    final v = this as A8<T>;
    return A8<T>.aa(
      data2 ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as A8<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is A8<T> &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as A8<T>;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as A8<T>;
    return 'A8<$T>{data2: ${v._dataVar}}';
  }
}

mixin B8Data<T> {
  static B8<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return B8<T>.bb(
      fromJsonT(json['data2']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as B8<T>;
    return <String, dynamic>{
      'data2': toJsonT(v._dataVar),
    };
  }

  B8<T> copyWith({
    T? data2,
  }) {
    final v = this as B8<T>;
    return B8<T>.bb(
      data2 ?? v._dataVar,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as B8<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is B8<T> &&
            (identical(other._dataVar, v._dataVar) || other._dataVar == v._dataVar));
  }

  @override
  int get hashCode {
    final v = this as B8<T>;
    return Object.hash(
      runtimeType,
      v._dataVar,
    );
  }

  @override
  String toString() {
    final v = this as B8<T>;
    return 'B8<$T>{data2: ${v._dataVar}}';
  }
}

mixin ComplexData<T> {
  static Complex<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Complex<T>(
      fromJsonT(json['data']),
      name: json['name'] as String?,
      age: (json['age'] as num?)?.toInt(),
      data2: fromJsonT(json['data2']),
      data3: MacroExt.decodeNullableGeneric(json['data3'], fromJsonT),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Complex<T>;
    return <String, dynamic>{
      'data': toJsonT(v.data),
      'name': ?v.name,
      'age': v.age,
      'data2': toJsonT(v.data2),
      'data3': ?MacroExt.encodeNullableGeneric(v._data3, toJsonT),
    };
  }

  Complex<T> copyWith({
    T? data,
    String? name,
    int? age,
    T? data2,
    T? data3,
  }) {
    final v = this as Complex<T>;
    return Complex<T>(
      data ?? v.data,
      name: name ?? v.name,
      age: age ?? v.age,
      data2: data2 ?? v.data2,
      data3: data3 ?? v._data3,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Complex<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Complex<T> &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.age, v.age) || other.age == v.age) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2) &&
            (identical(other._data3, v._data3) || other._data3 == v._data3));
  }

  @override
  int get hashCode {
    final v = this as Complex<T>;
    return Object.hash(
      runtimeType,
      v.data,
      v.name,
      v.age,
      v.data2,
      v._data3,
    );
  }

  @override
  String toString() {
    final v = this as Complex<T>;
    return 'Complex<$T>{data: ${v.data}, name: ${v.name}, age: ${v.age}, data2: ${v.data2}, data3: ${v._data3}}';
  }
}

mixin ComplexSubData<T> {
  static ComplexSub<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return ComplexSub<T>(
      fromJsonT(json['data']),
      name: json['name'] as String?,
      data2: fromJsonT(json['data2']),
      data3: MacroExt.decodeNullableGeneric(json['data3'], fromJsonT),
      age: (json['age'] as num?)?.toInt(),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as ComplexSub<T>;
    return <String, dynamic>{
      'data': toJsonT(v.data),
      'name': ?v.name,
      'data2': toJsonT(v.data2),
      'data3': ?MacroExt.encodeNullableGeneric(v._data3, toJsonT),
      'age': v.age,
    };
  }

  ComplexSub<T> copyWith({
    T? data,
    String? name,
    T? data2,
    T? data3,
    int? age,
  }) {
    final v = this as ComplexSub<T>;
    return ComplexSub<T>(
      data ?? v.data,
      name: name ?? v.name,
      data2: data2 ?? v.data2,
      data3: data3 ?? v._data3,
      age: age ?? v.age,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ComplexSub<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ComplexSub<T> &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.name, v.name) || other.name == v.name) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2) &&
            (identical(other._data3, v._data3) || other._data3 == v._data3) &&
            (identical(other.age, v.age) || other.age == v.age));
  }

  @override
  int get hashCode {
    final v = this as ComplexSub<T>;
    return Object.hash(
      runtimeType,
      v.data,
      v.name,
      v.data2,
      v._data3,
      v.age,
    );
  }

  @override
  String toString() {
    final v = this as ComplexSub<T>;
    return 'ComplexSub<$T>{data: ${v.data}, name: ${v.name}, data2: ${v.data2}, data3: ${v._data3}, age: ${v.age}}';
  }
}
