// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'self_ref_test.dart';

mixin ProfileGen1Data<T> {
  static ProfileGen1<T> fromJson<T>(
    Map<String, dynamic> json,
    T Function(Object? v) fromJsonT,
    int Function(Object? v) fromJsonData2,
    String Function(Object? v) fromJsonData3,
  ) {
    return ProfileGen1<T>(
      value: fromJsonT(json['value']),
      data: json['data'] == null
          ? null
          : ProfileGen1Data.fromJson<T>(json['data'] as Map<String, dynamic>, fromJsonT, fromJsonData2, fromJsonData3),
      data2: json['data2'] == null
          ? null
          : ProfileGen1Data.fromJson<int>(
              json['data2'] as Map<String, dynamic>,
              fromJsonData2,
              fromJsonData2,
              fromJsonData3,
            ),
      data3: json['data3'] == null
          ? null
          : ProfileGen1Data.fromJson<String>(
              json['data3'] as Map<String, dynamic>,
              fromJsonData3,
              fromJsonData2,
              fromJsonData3,
            ),
    );
  }

  Map<String, dynamic> toJson(
    Object? Function(T v) toJsonT,
    Object? Function(int v) toJsonData2,
    Object? Function(String v) toJsonData3,
  ) {
    final v = this as ProfileGen1<T>;
    return <String, dynamic>{
      'value': toJsonT(v.value),
      'data': ?v.data?.toJson(toJsonT, toJsonData2, toJsonData3),
      'data2': ?v.data2?.toJson(toJsonData2, toJsonData2, toJsonData3),
      'data3': ?v.data3?.toJson(toJsonData3, toJsonData2, toJsonData3),
    };
  }

  ProfileGen1<T> copyWith({
    T? value,
    ProfileGen1<T>? data,
    ProfileGen1<int>? data2,
    ProfileGen1<String>? data3,
  }) {
    final v = this as ProfileGen1<T>;
    return ProfileGen1<T>(
      value: value ?? v.value,
      data: data ?? v.data,
      data2: data2 ?? v.data2,
      data3: data3 ?? v.data3,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ProfileGen1<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ProfileGen1<T> &&
            (identical(other.value, v.value) || other.value == v.value) &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2) &&
            (identical(other.data3, v.data3) || other.data3 == v.data3));
  }

  @override
  int get hashCode {
    final v = this as ProfileGen1<T>;
    return Object.hash(
      runtimeType,
      v.value,
      v.data,
      v.data2,
      v.data3,
    );
  }

  @override
  String toString() {
    final v = this as ProfileGen1<T>;
    return 'ProfileGen1<$T>{value: ${v.value}, data: ${v.data}, data2: ${v.data2}, data3: ${v.data3}}';
  }
}

mixin ProfileGen2Data<T, V> {
  static ProfileGen2<T, V> fromJson<T, V>(
    Map<String, dynamic> json,
    T Function(Object? v) fromJsonT,
    V Function(Object? v) fromJsonV,
    String Function(Object? v) fromJsonData3,
    String Function(Object? v) fromJsonData4,
    String Function(Object? v) fromJsonData5,
    int Function(Object? v) fromJsonData6,
  ) {
    return ProfileGen2<T, V>(
      value: fromJsonT(json['value']),
      value2: fromJsonV(json['value2']),
      data: json['data'] == null
          ? null
          : ProfileGen2Data.fromJson<T, V>(
              json['data'] as Map<String, dynamic>,
              fromJsonT,
              fromJsonV,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
      data2: json['data2'] == null
          ? null
          : ProfileGen2Data.fromJson<V, T>(
              json['data2'] as Map<String, dynamic>,
              fromJsonV,
              fromJsonT,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
      data3: json['data3'] == null
          ? null
          : ProfileGen2Data.fromJson<String, T>(
              json['data3'] as Map<String, dynamic>,
              fromJsonData3,
              fromJsonT,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
      data4: json['data4'] == null
          ? null
          : ProfileGen2Data.fromJson<V, String>(
              json['data4'] as Map<String, dynamic>,
              fromJsonV,
              fromJsonData4,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
      data5: json['data5'] == null
          ? null
          : ProfileGen2Data.fromJson<String, String>(
              json['data5'] as Map<String, dynamic>,
              fromJsonData5,
              fromJsonData5,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
      data6: json['data6'] == null
          ? null
          : ProfileGen2Data.fromJson<int, int>(
              json['data6'] as Map<String, dynamic>,
              fromJsonData6,
              fromJsonData6,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
            ),
    );
  }

  Map<String, dynamic> toJson(
    Object? Function(T v) toJsonT,
    Object? Function(V v) toJsonV,
    Object? Function(String v) toJsonData3,
    Object? Function(String v) toJsonData4,
    Object? Function(String v) toJsonData5,
    Object? Function(int v) toJsonData6,
  ) {
    final v = this as ProfileGen2<T, V>;
    return <String, dynamic>{
      'value': toJsonT(v.value),
      'value2': toJsonV(v.value2),
      'data': ?v.data?.toJson(toJsonT, toJsonV, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
      'data2': ?v.data2?.toJson(toJsonV, toJsonT, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
      'data3': ?v.data3?.toJson(toJsonData3, toJsonT, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
      'data4': ?v.data4?.toJson(toJsonV, toJsonData4, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
      'data5': ?v.data5?.toJson(toJsonData5, toJsonData5, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
      'data6': ?v.data6?.toJson(toJsonData6, toJsonData6, toJsonData3, toJsonData4, toJsonData5, toJsonData6),
    };
  }

  ProfileGen2<T, V> copyWith({
    T? value,
    V? value2,
    ProfileGen2<T, V>? data,
    ProfileGen2<V, T>? data2,
    ProfileGen2<String, T>? data3,
    ProfileGen2<V, String>? data4,
    ProfileGen2<String, String>? data5,
    ProfileGen2<int, int>? data6,
  }) {
    final v = this as ProfileGen2<T, V>;
    return ProfileGen2<T, V>(
      value: value ?? v.value,
      value2: value2 ?? v.value2,
      data: data ?? v.data,
      data2: data2 ?? v.data2,
      data3: data3 ?? v.data3,
      data4: data4 ?? v.data4,
      data5: data5 ?? v.data5,
      data6: data6 ?? v.data6,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ProfileGen2<T, V>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ProfileGen2<T, V> &&
            (identical(other.value, v.value) || other.value == v.value) &&
            (identical(other.value2, v.value2) || other.value2 == v.value2) &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2) &&
            (identical(other.data3, v.data3) || other.data3 == v.data3) &&
            (identical(other.data4, v.data4) || other.data4 == v.data4) &&
            (identical(other.data5, v.data5) || other.data5 == v.data5) &&
            (identical(other.data6, v.data6) || other.data6 == v.data6));
  }

  @override
  int get hashCode {
    final v = this as ProfileGen2<T, V>;
    return Object.hash(
      runtimeType,
      v.value,
      v.value2,
      v.data,
      v.data2,
      v.data3,
      v.data4,
      v.data5,
      v.data6,
    );
  }

  @override
  String toString() {
    final v = this as ProfileGen2<T, V>;
    return 'ProfileGen2<$T,V>{value: ${v.value}, value2: ${v.value2}, data: ${v.data}, data2: ${v.data2}, data3: ${v.data3}, data4: ${v.data4}, data5: ${v.data5}, data6: ${v.data6}}';
  }
}

mixin ProfileGen3Data<T, F, V> {
  static ProfileGen3<T, F, V> fromJson<T, F, V>(
    Map<String, dynamic> json,
    T Function(Object? v) fromJsonT,
    F Function(Object? v) fromJsonF,
    V Function(Object? v) fromJsonV,
    String Function(Object? v) fromJsonData3,
    String Function(Object? v) fromJsonData4,
    String Function(Object? v) fromJsonData5,
    String Function(Object? v) fromJsonData6,
    String Function(Object? v) fromJsonData7,
  ) {
    return ProfileGen3<T, F, V>(
      value: fromJsonT(json['value']),
      value2: fromJsonF(json['value2']),
      value3: fromJsonV(json['value3']),
      data: json['data'] == null
          ? null
          : ProfileGen3Data.fromJson<T, F, V>(
              json['data'] as Map<String, dynamic>,
              fromJsonT,
              fromJsonF,
              fromJsonV,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data2: json['data2'] == null
          ? null
          : ProfileGen3Data.fromJson<V, F, T>(
              json['data2'] as Map<String, dynamic>,
              fromJsonV,
              fromJsonF,
              fromJsonT,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data3: json['data3'] == null
          ? null
          : ProfileGen3Data.fromJson<String, V, T>(
              json['data3'] as Map<String, dynamic>,
              fromJsonData3,
              fromJsonV,
              fromJsonT,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data4: json['data4'] == null
          ? null
          : ProfileGen3Data.fromJson<V, T, String>(
              json['data4'] as Map<String, dynamic>,
              fromJsonV,
              fromJsonT,
              fromJsonData4,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data5: json['data5'] == null
          ? null
          : ProfileGen3Data.fromJson<String, T, F>(
              json['data5'] as Map<String, dynamic>,
              fromJsonData5,
              fromJsonT,
              fromJsonF,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data6: json['data6'] == null
          ? null
          : ProfileGen3Data.fromJson<String, String, F>(
              json['data6'] as Map<String, dynamic>,
              fromJsonData6,
              fromJsonData6,
              fromJsonF,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
      data7: json['data7'] == null
          ? null
          : ProfileGen3Data.fromJson<String, String, String>(
              json['data7'] as Map<String, dynamic>,
              fromJsonData7,
              fromJsonData7,
              fromJsonData7,
              fromJsonData3,
              fromJsonData4,
              fromJsonData5,
              fromJsonData6,
              fromJsonData7,
            ),
    );
  }

  Map<String, dynamic> toJson(
    Object? Function(T v) toJsonT,
    Object? Function(F v) toJsonF,
    Object? Function(V v) toJsonV,
    Object? Function(String v) toJsonData3,
    Object? Function(String v) toJsonData4,
    Object? Function(String v) toJsonData5,
    Object? Function(String v) toJsonData6,
    Object? Function(String v) toJsonData7,
  ) {
    final v = this as ProfileGen3<T, F, V>;
    return <String, dynamic>{
      'value': toJsonT(v.value),
      'value2': toJsonF(v.value2),
      'value3': toJsonV(v.value3),
      'data': ?v.data?.toJson(
        toJsonT,
        toJsonF,
        toJsonV,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data2': ?v.data2?.toJson(
        toJsonV,
        toJsonF,
        toJsonT,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data3': ?v.data3?.toJson(
        toJsonData3,
        toJsonV,
        toJsonT,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data4': ?v.data4?.toJson(
        toJsonV,
        toJsonT,
        toJsonData4,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data5': ?v.data5?.toJson(
        toJsonData5,
        toJsonT,
        toJsonF,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data6': ?v.data6?.toJson(
        toJsonData6,
        toJsonData6,
        toJsonF,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
      'data7': ?v.data7?.toJson(
        toJsonData7,
        toJsonData7,
        toJsonData7,
        toJsonData3,
        toJsonData4,
        toJsonData5,
        toJsonData6,
        toJsonData7,
      ),
    };
  }

  ProfileGen3<T, F, V> copyWith({
    T? value,
    F? value2,
    V? value3,
    ProfileGen3<T, F, V>? data,
    ProfileGen3<V, F, T>? data2,
    ProfileGen3<String, V, T>? data3,
    ProfileGen3<V, T, String>? data4,
    ProfileGen3<String, T, F>? data5,
    ProfileGen3<String, String, F>? data6,
    ProfileGen3<String, String, String>? data7,
  }) {
    final v = this as ProfileGen3<T, F, V>;
    return ProfileGen3<T, F, V>(
      value: value ?? v.value,
      value2: value2 ?? v.value2,
      value3: value3 ?? v.value3,
      data: data ?? v.data,
      data2: data2 ?? v.data2,
      data3: data3 ?? v.data3,
      data4: data4 ?? v.data4,
      data5: data5 ?? v.data5,
      data6: data6 ?? v.data6,
      data7: data7 ?? v.data7,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ProfileGen3<T, F, V>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ProfileGen3<T, F, V> &&
            (identical(other.value, v.value) || other.value == v.value) &&
            (identical(other.value2, v.value2) || other.value2 == v.value2) &&
            (identical(other.value3, v.value3) || other.value3 == v.value3) &&
            (identical(other.data, v.data) || other.data == v.data) &&
            (identical(other.data2, v.data2) || other.data2 == v.data2) &&
            (identical(other.data3, v.data3) || other.data3 == v.data3) &&
            (identical(other.data4, v.data4) || other.data4 == v.data4) &&
            (identical(other.data5, v.data5) || other.data5 == v.data5) &&
            (identical(other.data6, v.data6) || other.data6 == v.data6) &&
            (identical(other.data7, v.data7) || other.data7 == v.data7));
  }

  @override
  int get hashCode {
    final v = this as ProfileGen3<T, F, V>;
    return Object.hash(
      runtimeType,
      v.value,
      v.value2,
      v.value3,
      v.data,
      v.data2,
      v.data3,
      v.data4,
      v.data5,
      v.data6,
      v.data7,
    );
  }

  @override
  String toString() {
    final v = this as ProfileGen3<T, F, V>;
    return 'ProfileGen3<$T,F,V>{value: ${v.value}, value2: ${v.value2}, value3: ${v.value3}, data: ${v.data}, data2: ${v.data2}, data3: ${v.data3}, data4: ${v.data4}, data5: ${v.data5}, data6: ${v.data6}, data7: ${v.data7}}';
  }
}
