// ignore_for_file: library_private_types_in_public_api
// Generated by AssetPathMacro: DO NOT MODIFY BY HAND

final class AssetPaths {
  const AssetPaths._();

  static const DsStore = 'assets/.DS_Store';
  static const butterfly = 'assets/butterfly.jpg';

  static const images = _Images._();
}

final class _Images {
  const _Images._();

  static const _DsStoreVal = 'assets/images/.DS_Store';

  String get DsStore => _DsStoreVal;
  static const _heroVal = 'assets/images/hero.jpg';

  String get hero => _heroVal;
  static const _flutterVal = 'assets/images/flutter.jpg';

  String get flutter => _flutterVal;
  static const _dartVal = 'assets/images/dart.svg';

  String get dart => _dartVal;
}
