// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'measure_time.dart';

mixin TodoData {
  static Todo fromJson(Map<String, dynamic> json) {
    return Todo(
      id: (json['id'] as num).toInt(),
      userId: (json['userId'] as num).toInt(),
      title: json['title'] as String,
      completed: json['completed'] as bool,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Todo;
    return <String, dynamic>{
      'id': v.id,
      'userId': v.userId,
      'title': v.title,
      'completed': v.completed,
    };
  }

  Todo copyWith({
    int? id,
    int? userId,
    String? title,
    bool? completed,
  }) {
    final v = this as Todo;
    return Todo(
      id: id ?? v.id,
      userId: userId ?? v.userId,
      title: title ?? v.title,
      completed: completed ?? v.completed,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Todo;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Todo &&
            (identical(other.id, v.id) || other.id == v.id) &&
            (identical(other.userId, v.userId) || other.userId == v.userId) &&
            (identical(other.title, v.title) || other.title == v.title) &&
            (identical(other.completed, v.completed) || other.completed == v.completed));
  }

  @override
  int get hashCode {
    final v = this as Todo;
    return Object.hash(
      runtimeType,
      v.id,
      v.userId,
      v.title,
      v.completed,
    );
  }

  @override
  String toString() {
    final v = this as Todo;
    return 'Todo{id: ${v.id}, userId: ${v.userId}, title: ${v.title}, completed: ${v.completed}}';
  }
}

mixin TodosData {
  static Todos fromJson(Map<String, dynamic> json) {
    return Todos(
      items: (json['items'] as List<dynamic>).map((e) => TodoData.fromJson(e as Map<String, dynamic>)).toList(),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Todos;
    return <String, dynamic>{
      'items': v.items.map((e) => e.toJson()).toList(),
    };
  }

  Todos copyWith({
    List<Todo>? items,
  }) {
    final v = this as Todos;
    return Todos(
      items: items ?? v.items,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Todos;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Todos &&
            const DeepCollectionEquality().equals(other.items, v.items));
  }

  @override
  int get hashCode {
    final v = this as Todos;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.items),
    );
  }

  @override
  String toString() {
    final v = this as Todos;
    return 'Todos{items: ${v.items}}';
  }
}

Future<(Todos, int)> getTodos() async {
  final s = Stopwatch()..start();
  try {
    final res = await _getTodos();
    return (res, (s..stop()).elapsedMicroseconds);
  } catch (_) {
    s.stop();
    rethrow;
  }
}

Future<(Todo, int)> getTodoById(int id) async {
  final s = Stopwatch()..start();
  try {
    final res = await _getTodoById(id);
    return (res, (s..stop()).elapsedMicroseconds);
  } catch (_) {
    s.stop();
    rethrow;
  }
}

Future<(Todo, int)> getTodoOfTimed({required int id}) async {
  final s = Stopwatch()..start();
  try {
    final res = await getTodoOf(id: id);
    return (res, (s..stop()).elapsedMicroseconds);
  } catch (_) {
    s.stop();
    rethrow;
  }
}

int syncFunctionsTimed([void Function(int i) fn = operation, bool? a = true, bool? c]) {
  final s = Stopwatch()..start();
  try {
    syncFunctions(fn, a, c);
    return (s..stop()).elapsedMicroseconds;
  } catch (_) {
    s.stop();
    rethrow;
  }
}

int syncFunctions2Timed(void Function(int i) fn, {bool a = false, bool b = true, required String c}) {
  final s = Stopwatch()..start();
  try {
    syncFunctions2(fn, a: a, b: b, c: c);
    return (s..stop()).elapsedMicroseconds;
  } catch (_) {
    s.stop();
    rethrow;
  }
}

int syncFunctions3Timed({
  bool a = false,
  bool b = true,
  required String c,
  void Function(int i) fn = operation,
  void Function(int i)? fn2,
}) {
  final s = Stopwatch()..start();
  try {
    syncFunctions3(a: a, b: b, c: c, fn: fn, fn2: fn2);
    return (s..stop()).elapsedMicroseconds;
  } catch (_) {
    s.stop();
    rethrow;
  }
}
