// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// dart format off

part of 'enum_map_test.dart';

mixin ClassAData {
  static ClassA fromJson(Map<String, dynamic> json) {
    return ClassA(
      (json['someVariable'] as Map<String, dynamic>).map(
        (k, e) => MapEntry(MacroExt.decodeEnum(EnumA.values, k, unknownValue: null), e as bool),
      ),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as ClassA;
    return <String, dynamic>{
      'someVariable': v.someVariable.map((k, e) => MapEntry(k.name, e)),
    };
  }

  ClassA copyWith({
    Map<EnumA, bool>? someVariable,
  }) {
    final v = this as ClassA;
    return ClassA(
      someVariable ?? v.someVariable,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ClassA;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ClassA &&
            const DeepCollectionEquality().equals(other.someVariable, v.someVariable));
  }

  @override
  int get hashCode {
    final v = this as ClassA;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.someVariable),
    );
  }

  @override
  String toString() {
    final v = this as ClassA;
    return 'ClassA{someVariable: ${v.someVariable}}';
  }
}

mixin ClassBData {
  static ClassB fromJson(Map<String, dynamic> json) {
    return ClassB(
      (json['someVariable'] as Map<String, dynamic>).map(
        (k, e) => MapEntry(
          MacroExt.decodeEnum(EnumA.values, k, unknownValue: null),
          MacroExt.decodeNullableEnum(EnumB.values, e, unknownValue: null),
        ),
      ),
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as ClassB;
    return <String, dynamic>{
      'someVariable': v.someVariable.map((k, e) => MapEntry(k.name, e?.name)),
    };
  }

  ClassB copyWith({
    Map<EnumA, EnumB?>? someVariable,
  }) {
    final v = this as ClassB;
    return ClassB(
      someVariable ?? v.someVariable,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as ClassB;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is ClassB &&
            const DeepCollectionEquality().equals(other.someVariable, v.someVariable));
  }

  @override
  int get hashCode {
    final v = this as ClassB;
    return Object.hash(
      runtimeType,
      const DeepCollectionEquality().hash(v.someVariable),
    );
  }

  @override
  String toString() {
    final v = this as ClassB;
    return 'ClassB{someVariable: ${v.someVariable}}';
  }
}
