// GENERATED BY Macro: DO NOT MODIFY BY HAND

part of 'selective_generation_test.dart';

mixin AData {
  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
    };
  }

  A copyWith({
    String? a,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
    );
  }
}

mixin BData {
  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is B && (identical(other.b, v.b) || other.b == v.b));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.b,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{b: ${v.b}}';
  }
}
