// coverage:ignore-file
// GENERATED BY Macro: DO NOT MODIFY BY HAND
// ignore_for_file: type=lint
// ignore_for_file: unused_element, unused_local_variable, unnecessary_overrides, deprecated_member_use, deprecated_member_use_from_same_package, use_function_type_syntax_for_parameters, unnecessary_const, avoid_init_to_null, invalid_override_different_default_values_named, prefer_expression_function_bodies, annotate_overrides, invalid_annotation_target, unnecessary_question_mark
// dart format off

part of 'selective_generation_test.dart';

mixin AData {
  Map<String, dynamic> toJson() {
    final v = this as A;
    return <String, dynamic>{
      'a': v.a,
    };
  }

  A copyWith({
    String? a,
  }) {
    final v = this as A;
    return A(
      a ?? v.a,
    );
  }
}

mixin BData {
  @override
  bool operator ==(Object other) {
    final v = this as B;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is B && (identical(other.b, v.b) || other.b == v.b));
  }

  @override
  int get hashCode {
    final v = this as B;
    return Object.hash(
      runtimeType,
      v.b,
    );
  }

  @override
  String toString() {
    final v = this as B;
    return 'B{b: ${v.b}}';
  }
}

mixin CData {
  static C fromJson(Map<String, dynamic> json) {
    return C(
      json['c'] as String?,
      json['c2'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as C;
    return <String, dynamic>{
      'c': ?v.c,
      'c2': ?v.c2,
    };
  }

  C copyWith({
    Option<String> c = const Option.undefined(),
    String? c2,
  }) {
    final v = this as C;
    return C(
      c.isUndefined ? v.c : c.casted(),
      c2 ?? v.c2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as C;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is C &&
            (identical(other.c, v.c) || other.c == v.c) &&
            (identical(other.c2, v.c2) || other.c2 == v.c2));
  }

  @override
  int get hashCode {
    final v = this as C;
    return Object.hash(
      runtimeType,
      v.c,
      v.c2,
    );
  }

  @override
  String toString() {
    final v = this as C;
    return 'C{c: ${v.c}, c2: ${v.c2}}';
  }
}

mixin EData {
  static E fromJson(Map<String, dynamic> json) {
    return E(
      json['e'] as String?,
      json['e2'] as String?,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as E;
    return <String, dynamic>{
      'e': ?v.e,
      'e2': ?v.e2,
    };
  }

  E copyWith({
    Option<String> e = const Option.undefined(),
    String? e2,
  }) {
    final v = this as E;
    return E(
      e.isUndefined ? v.e : e.casted(),
      e2 ?? v.e2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as E;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is E &&
            (identical(other.e, v.e) || other.e == v.e) &&
            (identical(other.e2, v.e2) || other.e2 == v.e2));
  }

  @override
  int get hashCode {
    final v = this as E;
    return Object.hash(
      runtimeType,
      v.e,
      v.e2,
    );
  }

  @override
  String toString() {
    final v = this as E;
    return 'E{e: ${v.e}, e2: ${v.e2}}';
  }
}

mixin IssueData {
  static Issue fromJson(Map<String, dynamic> json) {
    return Issue(
      name: json['name'] as String,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as Issue;
    return <String, dynamic>{
      'name': v.name,
    };
  }

  Issue copyWith({
    String? name,
  }) {
    final v = this as Issue;
    return Issue(
      name: name ?? v.name,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Issue;
    return identical(this, other) ||
        (other.runtimeType == runtimeType && other is Issue && (identical(other.name, v.name) || other.name == v.name));
  }

  @override
  int get hashCode {
    final v = this as Issue;
    return Object.hash(
      runtimeType,
      v.name,
    );
  }

  @override
  String toString() {
    final v = this as Issue;
    return 'Issue{name: ${v.name}}';
  }
}

mixin PaginatedData<T> {
  static Paginated<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Paginated<T>(
      value: fromJsonT(json['value']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Paginated<T>;
    return <String, dynamic>{
      'value': toJsonT(v.value),
    };
  }

  Paginated<T> copyWith({
    T? value,
  }) {
    final v = this as Paginated<T>;
    return Paginated<T>(
      value: value ?? v.value,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Paginated<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Paginated<T> &&
            (identical(other.value, v.value) || other.value == v.value));
  }

  @override
  int get hashCode {
    final v = this as Paginated<T>;
    return Object.hash(
      runtimeType,
      v.value,
    );
  }

  @override
  String toString() {
    final v = this as Paginated<T>;
    return 'Paginated<$T>{value: ${v.value}}';
  }
}

mixin Paginated2Data<T> {
  static Paginated2<T> fromJson<T>(Map<String, dynamic> json, T Function(Object? v) fromJsonT) {
    return Paginated2<T>(
      value: fromJsonT(json['value']),
    );
  }

  Map<String, dynamic> toJson(Object? Function(T v) toJsonT) {
    final v = this as Paginated2<T>;
    return <String, dynamic>{
      'value': toJsonT(v.value),
    };
  }

  Paginated2<T> copyWith({
    T? value,
  }) {
    final v = this as Paginated2<T>;
    return Paginated2<T>(
      value: value ?? v.value,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as Paginated2<T>;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is Paginated2<T> &&
            (identical(other.value, v.value) || other.value == v.value));
  }

  @override
  int get hashCode {
    final v = this as Paginated2<T>;
    return Object.hash(
      runtimeType,
      v.value,
    );
  }

  @override
  String toString() {
    final v = this as Paginated2<T>;
    return 'Paginated2<$T>{value: ${v.value}}';
  }
}

mixin RepoFullData {
  static RepoFull fromJson(Map<String, dynamic> json) {
    return RepoFull(
      issues: json['issues'] == null ? null : RepoFull.issuesFromJson(json['issues'] as Map<String, dynamic>?),
      issues2: null,
    );
  }

  Map<String, dynamic> toJson() {
    final v = this as RepoFull;
    return <String, dynamic>{
      'issues': ?RepoFull.issuesToJson(v.issues),
    };
  }

  RepoFull copyWith({
    Paginated<Issue>? issues,
    Paginated2<Issue>? issues2,
  }) {
    final v = this as RepoFull;
    return RepoFull(
      issues: issues ?? v.issues,
      issues2: issues2 ?? v.issues2,
    );
  }

  @override
  bool operator ==(Object other) {
    final v = this as RepoFull;
    return identical(this, other) ||
        (other.runtimeType == runtimeType &&
            other is RepoFull &&
            (identical(other.issues, v.issues) || other.issues == v.issues) &&
            (identical(other.issues2, v.issues2) || other.issues2 == v.issues2));
  }

  @override
  int get hashCode {
    final v = this as RepoFull;
    return Object.hash(
      runtimeType,
      v.issues,
      v.issues2,
    );
  }

  @override
  String toString() {
    final v = this as RepoFull;
    return 'RepoFull{issues: ${v.issues}, issues2: ${v.issues2}}';
  }
}
